/**
 * Generates CSS/SCSS/TS artifacts from tokens.json and validates WCAG contrast.
 * Run: `pnpm tokens` (Node >= 22.18 strips TypeScript types natively).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

type TokenTree = { [key: string]: string | TokenTree };

interface TokenFile {
  primitive: TokenTree;
  semantic: { base: TokenTree; light: TokenTree; dark: TokenTree };
  component: TokenTree;
}

interface FlatToken {
  path: string;
  value: string;
}

export interface TokenDoc {
  name: string;
  layer: 'primitive' | 'semantic' | 'component';
  light: string;
  dark: string;
}

const here = dirname(fileURLToPath(import.meta.url));
const libRoot = resolve(here, '..');
const tokens = JSON.parse(readFileSync(resolve(here, 'tokens.json'), 'utf8')) as TokenFile;

const REF = /\{([^}]+)\}/g;
const THEME_PROPERTIES = new Set(['color-scheme']);

function flatten(tree: TokenTree, prefix = ''): FlatToken[] {
  return Object.entries(tree).flatMap(([key, value]) => {
    if (key.startsWith('$')) return [];
    const path = prefix ? `${prefix}.${key}` : key;
    return typeof value === 'string' ? [{ path, value }] : flatten(value, path);
  });
}

const cssName = (layerPrefix: string, path: string): string =>
  `--ui-${layerPrefix}${path.replaceAll('.', '-')}`;

const primitives = flatten(tokens.primitive);
const primitiveMap = new Map(primitives.map((t) => [t.path, t.value]));
const base = flatten(tokens.semantic.base);
const light = flatten(tokens.semantic.light);
const dark = flatten(tokens.semantic.dark);
const component = flatten(tokens.component);

const semanticPaths = new Set([...base, ...light, ...dark].map((t) => t.path));

function assertSameKeys(a: FlatToken[], b: FlatToken[]): void {
  const aKeys = new Set(a.map((t) => t.path));
  const bKeys = new Set(b.map((t) => t.path));
  const missing = [...aKeys].filter((k) => !bKeys.has(k)).concat([...bKeys].filter((k) => !aKeys.has(k)));
  if (missing.length) throw new Error(`Light/dark themes differ in keys: ${missing.join(', ')}`);
}
assertSameKeys(light, dark);

/** Semantic values reference primitives; component values reference semantic tokens. */
function toCss(value: string, layer: 'semantic' | 'component'): string {
  return value.replace(REF, (_, path: string) => {
    if (layer === 'semantic') {
      if (!primitiveMap.has(path)) throw new Error(`Unknown primitive reference {${path}}`);
      return `var(${cssName('ref-', path)})`;
    }
    if (!semanticPaths.has(path)) throw new Error(`Component tokens must reference semantic tokens: {${path}}`);
    return `var(${cssName('', path)})`;
  });
}

function declarations(list: FlatToken[], layer: 'semantic' | 'component', indent = '  '): string {
  return list
    .map((t) =>
      THEME_PROPERTIES.has(t.path)
        ? `${indent}${t.path}: ${t.value};`
        : `${indent}${cssName('', t.path)}: ${toCss(t.value, layer)};`,
    )
    .join('\n');
}

const header = `/* Generated by tokens/build-tokens.ts from tokens.json. Do not edit by hand. */`;

const css = `${header}
:root {
${primitives.map((t) => `  ${cssName('ref-', t.path)}: ${t.value};`).join('\n')}
${declarations(base, 'semantic')}
}

:root,
[data-theme='light'] {
${declarations(light, 'semantic')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${declarations(dark, 'semantic', '    ')}
  }
}

[data-theme='dark'] {
${declarations(dark, 'semantic')}
}

/* Component tokens are re-declared on every themed scope so they follow nested themes. */
:root,
[data-theme] {
${declarations(component, 'component')}
}
`;

// ---- Contrast validation --------------------------------------------------

function resolveColor(theme: FlatToken[], path: string): string {
  const token = theme.find((t) => t.path === path) ?? base.find((t) => t.path === path);
  if (!token) throw new Error(`Contrast check: unknown token ${path}`);
  const ref = /^\{([^}]+)\}$/.exec(token.value);
  const value = ref ? primitiveMap.get(ref[1]) : token.value;
  if (!value || !/^#[0-9a-f]{6}$/i.test(value)) throw new Error(`Contrast check: ${path} is not a hex color`);
  return value;
}

function luminance(hex: string): number {
  const channels = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255);
  const [r, g, b] = channels.map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

function contrast(a: string, b: string): number {
  const [l1, l2] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (l1 + 0.05) / (l2 + 0.05);
}

const TEXT = 4.5;
const UI = 3;
const contrastPairs: [fg: string, bg: string, min: number][] = [
  ['color.text', 'color.bg', TEXT],
  ['color.text', 'color.surface', TEXT],
  ['color.text', 'color.surface-muted', TEXT],
  ['color.text', 'color.surface-active', TEXT],
  ['color.text-muted', 'color.bg', TEXT],
  ['color.text-muted', 'color.surface', TEXT],
  ['color.text-muted', 'color.surface-muted', TEXT],
  ['color.text-inverse', 'color.text-muted', TEXT],
  ['color.text-inverse', 'color.text', TEXT],
  ['color.text-subtle', 'color.surface', TEXT],
  ['color.primary-contrast', 'color.primary', TEXT],
  ['color.primary-contrast', 'color.primary-hover', TEXT],
  ['color.primary-contrast', 'color.primary-active', TEXT],
  ['color.danger-contrast', 'color.danger', TEXT],
  ['color.danger-contrast', 'color.danger-hover', TEXT],
  ['color.success-contrast', 'color.success', TEXT],
  ['color.warning-contrast', 'color.warning', TEXT],
  ['color.info-contrast', 'color.info', TEXT],
  ['color.primary-text', 'color.bg', TEXT],
  ['color.primary-text', 'color.primary-subtle', TEXT],
  ['color.danger-text', 'color.surface', TEXT],
  ['color.danger-text', 'color.danger-subtle', TEXT],
  ['color.success-text', 'color.success-subtle', TEXT],
  ['color.warning-text', 'color.warning-subtle', TEXT],
  ['color.info-text', 'color.info-subtle', TEXT],
  ['color.border-control', 'color.bg', UI],
  ['color.border-control', 'color.surface', UI],
  ['color.border-control', 'color.control-bg', UI],
  ['color.focus-ring', 'color.bg', UI],
  ['color.focus-ring', 'color.surface', UI],
  ['color.primary', 'color.surface', UI],
  ['color.danger', 'color.surface', UI],
];

const failures: string[] = [];
for (const [name, theme] of [['light', light], ['dark', dark]] as const) {
  for (const [fg, bg, min] of contrastPairs) {
    const ratio = contrast(resolveColor(theme, fg), resolveColor(theme, bg));
    if (ratio < min) failures.push(`[${name}] ${fg} on ${bg}: ${ratio.toFixed(2)} < ${min}`);
  }
}
if (failures.length) {
  console.error(`WCAG contrast check failed:\n  ${failures.join('\n  ')}`);
  process.exit(1);
}

// ---- Docs data -------------------------------------------------------------

/** Docs show semantic tokens with their resolved primitive values, e.g. `#4f46e5`. */
const resolvePrimitives = (value: string): string =>
  value.replace(REF, (_, path: string) => primitiveMap.get(path) ?? path);

const themeValue = (theme: FlatToken[], path: string): string =>
  resolvePrimitives(theme.find((t) => t.path === path)?.value ?? '');

const docs: TokenDoc[] = [
  ...primitives.map((t) => ({ name: cssName('ref-', t.path), layer: 'primitive' as const, light: t.value, dark: t.value })),
  ...base.map((t) => ({ name: cssName('', t.path), layer: 'semantic' as const, light: resolvePrimitives(t.value), dark: resolvePrimitives(t.value) })),
  ...light
    .filter((t) => !THEME_PROPERTIES.has(t.path))
    .map((t) => ({ name: cssName('', t.path), layer: 'semantic' as const, light: themeValue(light, t.path), dark: themeValue(dark, t.path) })),
  ...component.map((t) => ({ name: cssName('', t.path), layer: 'component' as const, light: toCss(t.value, 'component'), dark: toCss(t.value, 'component') })),
];

const ts = `${header}
export interface UiTokenDoc {
  name: string;
  layer: 'primitive' | 'semantic' | 'component';
  light: string;
  dark: string;
}

export const UI_TOKENS: readonly UiTokenDoc[] = ${JSON.stringify(docs, null, 2)};
`;

writeFileSync(resolve(libRoot, 'styles/tokens.css'), css);
writeFileSync(resolve(libRoot, 'styles/_tokens.scss'), css);
writeFileSync(resolve(here, 'tokens.generated.ts'), ts);

// README token table between markers.
const readmePath = resolve(libRoot, 'README.md');
const readme = readFileSync(readmePath, 'utf8');
const start = '<!-- tokens:start -->';
const end = '<!-- tokens:end -->';
if (readme.includes(start) && readme.includes(end)) {
  const rows = docs
    .filter((d) => d.layer !== 'primitive')
    .map((d) => `| \`${d.name}\` | ${d.layer} | \`${d.light}\` | \`${d.dark}\` |`)
    .join('\n');
  const table = `${start}\n| Token | Layer | Light | Dark |\n| --- | --- | --- | --- |\n${rows}\n${end}`;
  const updated = readme.replace(new RegExp(`${start}[\\s\\S]*${end}`), table);
  // Keep the README stable under `pnpm format`.
  const prettier = await import('prettier');
  const options = (await prettier.resolveConfig(readmePath)) ?? {};
  writeFileSync(readmePath, await prettier.format(updated, { ...options, filepath: readmePath }));
}

console.log(`Tokens: ${primitives.length} primitive, ${base.length + light.length} semantic, ${component.length} component. Contrast OK.`);
