/* Generated by tokens/build-tokens.mts from tokens.json. Do not edit by hand. */
export interface UiTokenDoc {
  name: string;
  layer: 'primitive' | 'semantic' | 'component';
  light: string;
  dark: string;
}

export const UI_TOKENS: readonly UiTokenDoc[] = [
  {
    "name": "--ui-ref-color-white",
    "layer": "primitive",
    "light": "#ffffff",
    "dark": "#ffffff"
  },
  {
    "name": "--ui-ref-color-black",
    "layer": "primitive",
    "light": "#000000",
    "dark": "#000000"
  },
  {
    "name": "--ui-ref-color-red-50",
    "layer": "primitive",
    "light": "#fef2f2",
    "dark": "#fef2f2"
  },
  {
    "name": "--ui-ref-color-red-100",
    "layer": "primitive",
    "light": "#fee2e2",
    "dark": "#fee2e2"
  },
  {
    "name": "--ui-ref-color-red-200",
    "layer": "primitive",
    "light": "#fecaca",
    "dark": "#fecaca"
  },
  {
    "name": "--ui-ref-color-red-300",
    "layer": "primitive",
    "light": "#fca5a5",
    "dark": "#fca5a5"
  },
  {
    "name": "--ui-ref-color-red-400",
    "layer": "primitive",
    "light": "#f87171",
    "dark": "#f87171"
  },
  {
    "name": "--ui-ref-color-red-500",
    "layer": "primitive",
    "light": "#ef4444",
    "dark": "#ef4444"
  },
  {
    "name": "--ui-ref-color-red-600",
    "layer": "primitive",
    "light": "#dc2626",
    "dark": "#dc2626"
  },
  {
    "name": "--ui-ref-color-red-700",
    "layer": "primitive",
    "light": "#b91c1c",
    "dark": "#b91c1c"
  },
  {
    "name": "--ui-ref-color-red-800",
    "layer": "primitive",
    "light": "#991b1b",
    "dark": "#991b1b"
  },
  {
    "name": "--ui-ref-color-red-900",
    "layer": "primitive",
    "light": "#7f1d1d",
    "dark": "#7f1d1d"
  },
  {
    "name": "--ui-ref-color-red-950",
    "layer": "primitive",
    "light": "#450a0a",
    "dark": "#450a0a"
  },
  {
    "name": "--ui-ref-color-green-50",
    "layer": "primitive",
    "light": "#e8f6ef",
    "dark": "#e8f6ef"
  },
  {
    "name": "--ui-ref-color-green-100",
    "layer": "primitive",
    "light": "#c9ebd9",
    "dark": "#c9ebd9"
  },
  {
    "name": "--ui-ref-color-green-200",
    "layer": "primitive",
    "light": "#95d6b4",
    "dark": "#95d6b4"
  },
  {
    "name": "--ui-ref-color-green-300",
    "layer": "primitive",
    "light": "#5fbf8f",
    "dark": "#5fbf8f"
  },
  {
    "name": "--ui-ref-color-green-400",
    "layer": "primitive",
    "light": "#3fae7c",
    "dark": "#3fae7c"
  },
  {
    "name": "--ui-ref-color-green-500",
    "layer": "primitive",
    "light": "#0f9a61",
    "dark": "#0f9a61"
  },
  {
    "name": "--ui-ref-color-green-600",
    "layer": "primitive",
    "light": "#008752",
    "dark": "#008752"
  },
  {
    "name": "--ui-ref-color-green-700",
    "layer": "primitive",
    "light": "#006c42",
    "dark": "#006c42"
  },
  {
    "name": "--ui-ref-color-green-800",
    "layer": "primitive",
    "light": "#055636",
    "dark": "#055636"
  },
  {
    "name": "--ui-ref-color-green-900",
    "layer": "primitive",
    "light": "#07472e",
    "dark": "#07472e"
  },
  {
    "name": "--ui-ref-color-green-950",
    "layer": "primitive",
    "light": "#032819",
    "dark": "#032819"
  },
  {
    "name": "--ui-ref-color-brand-50",
    "layer": "primitive",
    "light": "#e9f4fc",
    "dark": "#e9f4fc"
  },
  {
    "name": "--ui-ref-color-brand-100",
    "layer": "primitive",
    "light": "#d3e9fa",
    "dark": "#d3e9fa"
  },
  {
    "name": "--ui-ref-color-brand-200",
    "layer": "primitive",
    "light": "#a8d3f6",
    "dark": "#a8d3f6"
  },
  {
    "name": "--ui-ref-color-brand-300",
    "layer": "primitive",
    "light": "#72b8f2",
    "dark": "#72b8f2"
  },
  {
    "name": "--ui-ref-color-brand-400",
    "layer": "primitive",
    "light": "#4aa3ef",
    "dark": "#4aa3ef"
  },
  {
    "name": "--ui-ref-color-brand-500",
    "layer": "primitive",
    "light": "#2490ed",
    "dark": "#2490ed"
  },
  {
    "name": "--ui-ref-color-brand-600",
    "layer": "primitive",
    "light": "#1a74c9",
    "dark": "#1a74c9"
  },
  {
    "name": "--ui-ref-color-brand-700",
    "layer": "primitive",
    "light": "#155ea6",
    "dark": "#155ea6"
  },
  {
    "name": "--ui-ref-color-brand-800",
    "layer": "primitive",
    "light": "#004b9e",
    "dark": "#004b9e"
  },
  {
    "name": "--ui-ref-color-brand-900",
    "layer": "primitive",
    "light": "#0d3d6e",
    "dark": "#0d3d6e"
  },
  {
    "name": "--ui-ref-color-brand-950",
    "layer": "primitive",
    "light": "#0a2747",
    "dark": "#0a2747"
  },
  {
    "name": "--ui-ref-color-gray-50",
    "layer": "primitive",
    "light": "#f8f9fb",
    "dark": "#f8f9fb"
  },
  {
    "name": "--ui-ref-color-gray-100",
    "layer": "primitive",
    "light": "#f1f3f6",
    "dark": "#f1f3f6"
  },
  {
    "name": "--ui-ref-color-gray-200",
    "layer": "primitive",
    "light": "#e4e7ed",
    "dark": "#e4e7ed"
  },
  {
    "name": "--ui-ref-color-gray-300",
    "layer": "primitive",
    "light": "#cdd2db",
    "dark": "#cdd2db"
  },
  {
    "name": "--ui-ref-color-gray-400",
    "layer": "primitive",
    "light": "#a7acaf",
    "dark": "#a7acaf"
  },
  {
    "name": "--ui-ref-color-gray-500",
    "layer": "primitive",
    "light": "#848d9d",
    "dark": "#848d9d"
  },
  {
    "name": "--ui-ref-color-gray-600",
    "layer": "primitive",
    "light": "#636d7e",
    "dark": "#636d7e"
  },
  {
    "name": "--ui-ref-color-gray-700",
    "layer": "primitive",
    "light": "#4a5466",
    "dark": "#4a5466"
  },
  {
    "name": "--ui-ref-color-gray-750",
    "layer": "primitive",
    "light": "#364054",
    "dark": "#364054"
  },
  {
    "name": "--ui-ref-color-gray-800",
    "layer": "primitive",
    "light": "#2b3549",
    "dark": "#2b3549"
  },
  {
    "name": "--ui-ref-color-gray-900",
    "layer": "primitive",
    "light": "#1d2535",
    "dark": "#1d2535"
  },
  {
    "name": "--ui-ref-color-gray-950",
    "layer": "primitive",
    "light": "#111723",
    "dark": "#111723"
  },
  {
    "name": "--ui-ref-color-olive-50",
    "layer": "primitive",
    "light": "#faf8e8",
    "dark": "#faf8e8"
  },
  {
    "name": "--ui-ref-color-olive-100",
    "layer": "primitive",
    "light": "#f3efc6",
    "dark": "#f3efc6"
  },
  {
    "name": "--ui-ref-color-olive-200",
    "layer": "primitive",
    "light": "#e6dd8e",
    "dark": "#e6dd8e"
  },
  {
    "name": "--ui-ref-color-olive-300",
    "layer": "primitive",
    "light": "#d4c65a",
    "dark": "#d4c65a"
  },
  {
    "name": "--ui-ref-color-olive-400",
    "layer": "primitive",
    "light": "#bfae38",
    "dark": "#bfae38"
  },
  {
    "name": "--ui-ref-color-olive-500",
    "layer": "primitive",
    "light": "#a19329",
    "dark": "#a19329"
  },
  {
    "name": "--ui-ref-color-olive-600",
    "layer": "primitive",
    "light": "#857820",
    "dark": "#857820"
  },
  {
    "name": "--ui-ref-color-olive-700",
    "layer": "primitive",
    "light": "#685e1b",
    "dark": "#685e1b"
  },
  {
    "name": "--ui-ref-color-olive-800",
    "layer": "primitive",
    "light": "#554c1a",
    "dark": "#554c1a"
  },
  {
    "name": "--ui-ref-color-olive-900",
    "layer": "primitive",
    "light": "#483f19",
    "dark": "#483f19"
  },
  {
    "name": "--ui-ref-color-olive-950",
    "layer": "primitive",
    "light": "#29230a",
    "dark": "#29230a"
  },
  {
    "name": "--ui-ref-color-purple-100",
    "layer": "primitive",
    "light": "#ede9fe",
    "dark": "#ede9fe"
  },
  {
    "name": "--ui-ref-color-purple-200",
    "layer": "primitive",
    "light": "#ddd6fe",
    "dark": "#ddd6fe"
  },
  {
    "name": "--ui-ref-color-purple-800",
    "layer": "primitive",
    "light": "#5b21b6",
    "dark": "#5b21b6"
  },
  {
    "name": "--ui-ref-color-purple-900",
    "layer": "primitive",
    "light": "#4c1d95",
    "dark": "#4c1d95"
  },
  {
    "name": "--ui-ref-color-teal-100",
    "layer": "primitive",
    "light": "#ccfbf1",
    "dark": "#ccfbf1"
  },
  {
    "name": "--ui-ref-color-teal-200",
    "layer": "primitive",
    "light": "#99f6e4",
    "dark": "#99f6e4"
  },
  {
    "name": "--ui-ref-color-teal-800",
    "layer": "primitive",
    "light": "#115e59",
    "dark": "#115e59"
  },
  {
    "name": "--ui-ref-color-teal-900",
    "layer": "primitive",
    "light": "#134e4a",
    "dark": "#134e4a"
  },
  {
    "name": "--ui-ref-color-orange-100",
    "layer": "primitive",
    "light": "#ffedd5",
    "dark": "#ffedd5"
  },
  {
    "name": "--ui-ref-color-orange-200",
    "layer": "primitive",
    "light": "#fed7aa",
    "dark": "#fed7aa"
  },
  {
    "name": "--ui-ref-color-orange-800",
    "layer": "primitive",
    "light": "#9a3412",
    "dark": "#9a3412"
  },
  {
    "name": "--ui-ref-color-orange-900",
    "layer": "primitive",
    "light": "#7c2d12",
    "dark": "#7c2d12"
  },
  {
    "name": "--ui-ref-color-pink-100",
    "layer": "primitive",
    "light": "#fce7f3",
    "dark": "#fce7f3"
  },
  {
    "name": "--ui-ref-color-pink-200",
    "layer": "primitive",
    "light": "#fbcfe8",
    "dark": "#fbcfe8"
  },
  {
    "name": "--ui-ref-color-pink-800",
    "layer": "primitive",
    "light": "#9d174d",
    "dark": "#9d174d"
  },
  {
    "name": "--ui-ref-color-pink-900",
    "layer": "primitive",
    "light": "#831843",
    "dark": "#831843"
  },
  {
    "name": "--ui-ref-color-scrim-light",
    "layer": "primitive",
    "light": "rgb(15 23 42 / 0.5)",
    "dark": "rgb(15 23 42 / 0.5)"
  },
  {
    "name": "--ui-ref-color-scrim-dark",
    "layer": "primitive",
    "light": "rgb(0 0 0 / 0.6)",
    "dark": "rgb(0 0 0 / 0.6)"
  },
  {
    "name": "--ui-ref-space-0",
    "layer": "primitive",
    "light": "0",
    "dark": "0"
  },
  {
    "name": "--ui-ref-space-1",
    "layer": "primitive",
    "light": "0.25rem",
    "dark": "0.25rem"
  },
  {
    "name": "--ui-ref-space-2",
    "layer": "primitive",
    "light": "0.5rem",
    "dark": "0.5rem"
  },
  {
    "name": "--ui-ref-space-3",
    "layer": "primitive",
    "light": "0.75rem",
    "dark": "0.75rem"
  },
  {
    "name": "--ui-ref-space-4",
    "layer": "primitive",
    "light": "1rem",
    "dark": "1rem"
  },
  {
    "name": "--ui-ref-space-5",
    "layer": "primitive",
    "light": "1.25rem",
    "dark": "1.25rem"
  },
  {
    "name": "--ui-ref-space-6",
    "layer": "primitive",
    "light": "1.5rem",
    "dark": "1.5rem"
  },
  {
    "name": "--ui-ref-space-8",
    "layer": "primitive",
    "light": "2rem",
    "dark": "2rem"
  },
  {
    "name": "--ui-ref-space-9",
    "layer": "primitive",
    "light": "2.25rem",
    "dark": "2.25rem"
  },
  {
    "name": "--ui-ref-space-10",
    "layer": "primitive",
    "light": "2.5rem",
    "dark": "2.5rem"
  },
  {
    "name": "--ui-ref-space-12",
    "layer": "primitive",
    "light": "3rem",
    "dark": "3rem"
  },
  {
    "name": "--ui-ref-space-16",
    "layer": "primitive",
    "light": "4rem",
    "dark": "4rem"
  },
  {
    "name": "--ui-ref-space-0-5",
    "layer": "primitive",
    "light": "0.125rem",
    "dark": "0.125rem"
  },
  {
    "name": "--ui-ref-space-1-5",
    "layer": "primitive",
    "light": "0.375rem",
    "dark": "0.375rem"
  },
  {
    "name": "--ui-ref-space-2-5",
    "layer": "primitive",
    "light": "0.625rem",
    "dark": "0.625rem"
  },
  {
    "name": "--ui-ref-size-3",
    "layer": "primitive",
    "light": "0.75rem",
    "dark": "0.75rem"
  },
  {
    "name": "--ui-ref-size-4",
    "layer": "primitive",
    "light": "1rem",
    "dark": "1rem"
  },
  {
    "name": "--ui-ref-size-5",
    "layer": "primitive",
    "light": "1.25rem",
    "dark": "1.25rem"
  },
  {
    "name": "--ui-ref-size-6",
    "layer": "primitive",
    "light": "1.5rem",
    "dark": "1.5rem"
  },
  {
    "name": "--ui-ref-size-8",
    "layer": "primitive",
    "light": "2rem",
    "dark": "2rem"
  },
  {
    "name": "--ui-ref-size-9",
    "layer": "primitive",
    "light": "2.25rem",
    "dark": "2.25rem"
  },
  {
    "name": "--ui-ref-size-10",
    "layer": "primitive",
    "light": "2.5rem",
    "dark": "2.5rem"
  },
  {
    "name": "--ui-ref-size-11",
    "layer": "primitive",
    "light": "2.75rem",
    "dark": "2.75rem"
  },
  {
    "name": "--ui-ref-size-12",
    "layer": "primitive",
    "light": "3rem",
    "dark": "3rem"
  },
  {
    "name": "--ui-ref-size-48",
    "layer": "primitive",
    "light": "12rem",
    "dark": "12rem"
  },
  {
    "name": "--ui-ref-size-60",
    "layer": "primitive",
    "light": "15rem",
    "dark": "15rem"
  },
  {
    "name": "--ui-ref-size-72",
    "layer": "primitive",
    "light": "18rem",
    "dark": "18rem"
  },
  {
    "name": "--ui-ref-size-80",
    "layer": "primitive",
    "light": "20rem",
    "dark": "20rem"
  },
  {
    "name": "--ui-ref-size-96",
    "layer": "primitive",
    "light": "24rem",
    "dark": "24rem"
  },
  {
    "name": "--ui-ref-size-100",
    "layer": "primitive",
    "light": "25rem",
    "dark": "25rem"
  },
  {
    "name": "--ui-ref-size-140",
    "layer": "primitive",
    "light": "35rem",
    "dark": "35rem"
  },
  {
    "name": "--ui-ref-size-200",
    "layer": "primitive",
    "light": "50rem",
    "dark": "50rem"
  },
  {
    "name": "--ui-ref-size-px",
    "layer": "primitive",
    "light": "1px",
    "dark": "1px"
  },
  {
    "name": "--ui-ref-size-2px",
    "layer": "primitive",
    "light": "2px",
    "dark": "2px"
  },
  {
    "name": "--ui-ref-size-3-5",
    "layer": "primitive",
    "light": "0.875rem",
    "dark": "0.875rem"
  },
  {
    "name": "--ui-ref-size-4-5",
    "layer": "primitive",
    "light": "1.125rem",
    "dark": "1.125rem"
  },
  {
    "name": "--ui-ref-em-1",
    "layer": "primitive",
    "light": "1em",
    "dark": "1em"
  },
  {
    "name": "--ui-ref-em-5",
    "layer": "primitive",
    "light": "5em",
    "dark": "5em"
  },
  {
    "name": "--ui-ref-em-6",
    "layer": "primitive",
    "light": "6em",
    "dark": "6em"
  },
  {
    "name": "--ui-ref-em-0-8",
    "layer": "primitive",
    "light": "0.8em",
    "dark": "0.8em"
  },
  {
    "name": "--ui-ref-em-2-5",
    "layer": "primitive",
    "light": "2.5em",
    "dark": "2.5em"
  },
  {
    "name": "--ui-ref-em-0-4",
    "layer": "primitive",
    "light": "0.4em",
    "dark": "0.4em"
  },
  {
    "name": "--ui-ref-radius-none",
    "layer": "primitive",
    "light": "0",
    "dark": "0"
  },
  {
    "name": "--ui-ref-radius-sm",
    "layer": "primitive",
    "light": "0.25rem",
    "dark": "0.25rem"
  },
  {
    "name": "--ui-ref-radius-md",
    "layer": "primitive",
    "light": "0.375rem",
    "dark": "0.375rem"
  },
  {
    "name": "--ui-ref-radius-lg",
    "layer": "primitive",
    "light": "0.5rem",
    "dark": "0.5rem"
  },
  {
    "name": "--ui-ref-radius-xl",
    "layer": "primitive",
    "light": "0.75rem",
    "dark": "0.75rem"
  },
  {
    "name": "--ui-ref-radius-full",
    "layer": "primitive",
    "light": "9999px",
    "dark": "9999px"
  },
  {
    "name": "--ui-ref-font-family-sans",
    "layer": "primitive",
    "light": "Assistant, Roboto, \"Helvetica Neue\", sans-serif",
    "dark": "Assistant, Roboto, \"Helvetica Neue\", sans-serif"
  },
  {
    "name": "--ui-ref-font-family-mono",
    "layer": "primitive",
    "light": "ui-monospace, 'JetBrains Mono', 'Cascadia Code', Consolas, monospace",
    "dark": "ui-monospace, 'JetBrains Mono', 'Cascadia Code', Consolas, monospace"
  },
  {
    "name": "--ui-ref-font-size-xs",
    "layer": "primitive",
    "light": "0.75rem",
    "dark": "0.75rem"
  },
  {
    "name": "--ui-ref-font-size-sm",
    "layer": "primitive",
    "light": "0.875rem",
    "dark": "0.875rem"
  },
  {
    "name": "--ui-ref-font-size-md",
    "layer": "primitive",
    "light": "1rem",
    "dark": "1rem"
  },
  {
    "name": "--ui-ref-font-size-lg",
    "layer": "primitive",
    "light": "1.125rem",
    "dark": "1.125rem"
  },
  {
    "name": "--ui-ref-font-size-xl",
    "layer": "primitive",
    "light": "1.25rem",
    "dark": "1.25rem"
  },
  {
    "name": "--ui-ref-font-size-2xl",
    "layer": "primitive",
    "light": "1.5rem",
    "dark": "1.5rem"
  },
  {
    "name": "--ui-ref-font-size-3xl",
    "layer": "primitive",
    "light": "1.875rem",
    "dark": "1.875rem"
  },
  {
    "name": "--ui-ref-font-size-4xl",
    "layer": "primitive",
    "light": "2.25rem",
    "dark": "2.25rem"
  },
  {
    "name": "--ui-ref-font-weight-regular",
    "layer": "primitive",
    "light": "400",
    "dark": "400"
  },
  {
    "name": "--ui-ref-font-weight-medium",
    "layer": "primitive",
    "light": "500",
    "dark": "500"
  },
  {
    "name": "--ui-ref-font-weight-semibold",
    "layer": "primitive",
    "light": "600",
    "dark": "600"
  },
  {
    "name": "--ui-ref-font-weight-bold",
    "layer": "primitive",
    "light": "700",
    "dark": "700"
  },
  {
    "name": "--ui-ref-line-height-tight",
    "layer": "primitive",
    "light": "1.25",
    "dark": "1.25"
  },
  {
    "name": "--ui-ref-line-height-snug",
    "layer": "primitive",
    "light": "1.375",
    "dark": "1.375"
  },
  {
    "name": "--ui-ref-line-height-normal",
    "layer": "primitive",
    "light": "1.5",
    "dark": "1.5"
  },
  {
    "name": "--ui-ref-shadow-sm",
    "layer": "primitive",
    "light": "0 1px 2px 0 rgb(15 23 42 / 0.06)",
    "dark": "0 1px 2px 0 rgb(15 23 42 / 0.06)"
  },
  {
    "name": "--ui-ref-shadow-md",
    "layer": "primitive",
    "light": "0 4px 8px -2px rgb(15 23 42 / 0.10), 0 2px 4px -2px rgb(15 23 42 / 0.06)",
    "dark": "0 4px 8px -2px rgb(15 23 42 / 0.10), 0 2px 4px -2px rgb(15 23 42 / 0.06)"
  },
  {
    "name": "--ui-ref-shadow-lg",
    "layer": "primitive",
    "light": "0 12px 24px -6px rgb(15 23 42 / 0.16), 0 4px 8px -4px rgb(15 23 42 / 0.08)",
    "dark": "0 12px 24px -6px rgb(15 23 42 / 0.16), 0 4px 8px -4px rgb(15 23 42 / 0.08)"
  },
  {
    "name": "--ui-ref-shadow-dark-sm",
    "layer": "primitive",
    "light": "0 1px 2px 0 rgb(0 0 0 / 0.4)",
    "dark": "0 1px 2px 0 rgb(0 0 0 / 0.4)"
  },
  {
    "name": "--ui-ref-shadow-dark-md",
    "layer": "primitive",
    "light": "0 4px 8px -2px rgb(0 0 0 / 0.5)",
    "dark": "0 4px 8px -2px rgb(0 0 0 / 0.5)"
  },
  {
    "name": "--ui-ref-shadow-dark-lg",
    "layer": "primitive",
    "light": "0 12px 24px -6px rgb(0 0 0 / 0.6)",
    "dark": "0 12px 24px -6px rgb(0 0 0 / 0.6)"
  },
  {
    "name": "--ui-ref-z-sticky",
    "layer": "primitive",
    "light": "1100",
    "dark": "1100"
  },
  {
    "name": "--ui-ref-duration-instant",
    "layer": "primitive",
    "light": "50ms",
    "dark": "50ms"
  },
  {
    "name": "--ui-ref-duration-fast",
    "layer": "primitive",
    "light": "120ms",
    "dark": "120ms"
  },
  {
    "name": "--ui-ref-duration-normal",
    "layer": "primitive",
    "light": "200ms",
    "dark": "200ms"
  },
  {
    "name": "--ui-ref-duration-slow",
    "layer": "primitive",
    "light": "320ms",
    "dark": "320ms"
  },
  {
    "name": "--ui-ref-easing-standard",
    "layer": "primitive",
    "light": "cubic-bezier(0.2, 0, 0, 1)",
    "dark": "cubic-bezier(0.2, 0, 0, 1)"
  },
  {
    "name": "--ui-ref-easing-enter",
    "layer": "primitive",
    "light": "cubic-bezier(0, 0, 0.2, 1)",
    "dark": "cubic-bezier(0, 0, 0.2, 1)"
  },
  {
    "name": "--ui-ref-easing-exit",
    "layer": "primitive",
    "light": "cubic-bezier(0.4, 0, 1, 1)",
    "dark": "cubic-bezier(0.4, 0, 1, 1)"
  },
  {
    "name": "--ui-font-family-sans",
    "layer": "semantic",
    "light": "Assistant, Roboto, \"Helvetica Neue\", sans-serif",
    "dark": "Assistant, Roboto, \"Helvetica Neue\", sans-serif"
  },
  {
    "name": "--ui-font-family-mono",
    "layer": "semantic",
    "light": "ui-monospace, 'JetBrains Mono', 'Cascadia Code', Consolas, monospace",
    "dark": "ui-monospace, 'JetBrains Mono', 'Cascadia Code', Consolas, monospace"
  },
  {
    "name": "--ui-font-size-xs",
    "layer": "semantic",
    "light": "0.75rem",
    "dark": "0.75rem"
  },
  {
    "name": "--ui-font-size-sm",
    "layer": "semantic",
    "light": "0.875rem",
    "dark": "0.875rem"
  },
  {
    "name": "--ui-font-size-md",
    "layer": "semantic",
    "light": "1rem",
    "dark": "1rem"
  },
  {
    "name": "--ui-font-size-lg",
    "layer": "semantic",
    "light": "1.125rem",
    "dark": "1.125rem"
  },
  {
    "name": "--ui-font-size-xl",
    "layer": "semantic",
    "light": "1.25rem",
    "dark": "1.25rem"
  },
  {
    "name": "--ui-font-size-2xl",
    "layer": "semantic",
    "light": "1.5rem",
    "dark": "1.5rem"
  },
  {
    "name": "--ui-font-size-3xl",
    "layer": "semantic",
    "light": "1.875rem",
    "dark": "1.875rem"
  },
  {
    "name": "--ui-font-size-4xl",
    "layer": "semantic",
    "light": "2.25rem",
    "dark": "2.25rem"
  },
  {
    "name": "--ui-font-weight-regular",
    "layer": "semantic",
    "light": "400",
    "dark": "400"
  },
  {
    "name": "--ui-font-weight-medium",
    "layer": "semantic",
    "light": "500",
    "dark": "500"
  },
  {
    "name": "--ui-font-weight-semibold",
    "layer": "semantic",
    "light": "600",
    "dark": "600"
  },
  {
    "name": "--ui-font-weight-bold",
    "layer": "semantic",
    "light": "700",
    "dark": "700"
  },
  {
    "name": "--ui-line-height-tight",
    "layer": "semantic",
    "light": "1.25",
    "dark": "1.25"
  },
  {
    "name": "--ui-line-height-snug",
    "layer": "semantic",
    "light": "1.375",
    "dark": "1.375"
  },
  {
    "name": "--ui-line-height-normal",
    "layer": "semantic",
    "light": "1.5",
    "dark": "1.5"
  },
  {
    "name": "--ui-space-3xs",
    "layer": "semantic",
    "light": "0.125rem",
    "dark": "0.125rem"
  },
  {
    "name": "--ui-space-2xs",
    "layer": "semantic",
    "light": "0.25rem",
    "dark": "0.25rem"
  },
  {
    "name": "--ui-space-xs",
    "layer": "semantic",
    "light": "0.375rem",
    "dark": "0.375rem"
  },
  {
    "name": "--ui-space-sm",
    "layer": "semantic",
    "light": "0.5rem",
    "dark": "0.5rem"
  },
  {
    "name": "--ui-space-md",
    "layer": "semantic",
    "light": "0.75rem",
    "dark": "0.75rem"
  },
  {
    "name": "--ui-space-lg",
    "layer": "semantic",
    "light": "1rem",
    "dark": "1rem"
  },
  {
    "name": "--ui-space-xl",
    "layer": "semantic",
    "light": "1.5rem",
    "dark": "1.5rem"
  },
  {
    "name": "--ui-space-2xl",
    "layer": "semantic",
    "light": "2rem",
    "dark": "2rem"
  },
  {
    "name": "--ui-space-3xl",
    "layer": "semantic",
    "light": "3rem",
    "dark": "3rem"
  },
  {
    "name": "--ui-radius-sm",
    "layer": "semantic",
    "light": "0.25rem",
    "dark": "0.25rem"
  },
  {
    "name": "--ui-radius-control",
    "layer": "semantic",
    "light": "0.375rem",
    "dark": "0.375rem"
  },
  {
    "name": "--ui-radius-container",
    "layer": "semantic",
    "light": "0.5rem",
    "dark": "0.5rem"
  },
  {
    "name": "--ui-radius-full",
    "layer": "semantic",
    "light": "9999px",
    "dark": "9999px"
  },
  {
    "name": "--ui-border-width-default",
    "layer": "semantic",
    "light": "1px",
    "dark": "1px"
  },
  {
    "name": "--ui-border-width-strong",
    "layer": "semantic",
    "light": "2px",
    "dark": "2px"
  },
  {
    "name": "--ui-focus-ring-width",
    "layer": "semantic",
    "light": "2px",
    "dark": "2px"
  },
  {
    "name": "--ui-focus-ring-offset",
    "layer": "semantic",
    "light": "2px",
    "dark": "2px"
  },
  {
    "name": "--ui-control-height-sm",
    "layer": "semantic",
    "light": "2rem",
    "dark": "2rem"
  },
  {
    "name": "--ui-control-height-md",
    "layer": "semantic",
    "light": "2.5rem",
    "dark": "2.5rem"
  },
  {
    "name": "--ui-control-height-lg",
    "layer": "semantic",
    "light": "2.75rem",
    "dark": "2.75rem"
  },
  {
    "name": "--ui-control-padding-inline-sm",
    "layer": "semantic",
    "light": "0.625rem",
    "dark": "0.625rem"
  },
  {
    "name": "--ui-control-padding-inline-md",
    "layer": "semantic",
    "light": "0.75rem",
    "dark": "0.75rem"
  },
  {
    "name": "--ui-control-padding-inline-lg",
    "layer": "semantic",
    "light": "1rem",
    "dark": "1rem"
  },
  {
    "name": "--ui-control-font-size-sm",
    "layer": "semantic",
    "light": "0.875rem",
    "dark": "0.875rem"
  },
  {
    "name": "--ui-control-font-size-md",
    "layer": "semantic",
    "light": "0.875rem",
    "dark": "0.875rem"
  },
  {
    "name": "--ui-control-font-size-lg",
    "layer": "semantic",
    "light": "1rem",
    "dark": "1rem"
  },
  {
    "name": "--ui-control-gap-sm",
    "layer": "semantic",
    "light": "0.375rem",
    "dark": "0.375rem"
  },
  {
    "name": "--ui-control-gap-md",
    "layer": "semantic",
    "light": "0.5rem",
    "dark": "0.5rem"
  },
  {
    "name": "--ui-control-gap-lg",
    "layer": "semantic",
    "light": "0.625rem",
    "dark": "0.625rem"
  },
  {
    "name": "--ui-icon-size-sm",
    "layer": "semantic",
    "light": "1rem",
    "dark": "1rem"
  },
  {
    "name": "--ui-icon-size-md",
    "layer": "semantic",
    "light": "1.25rem",
    "dark": "1.25rem"
  },
  {
    "name": "--ui-icon-size-lg",
    "layer": "semantic",
    "light": "1.5rem",
    "dark": "1.5rem"
  },
  {
    "name": "--ui-container-width-xs",
    "layer": "semantic",
    "light": "12rem",
    "dark": "12rem"
  },
  {
    "name": "--ui-container-width-sm",
    "layer": "semantic",
    "light": "15rem",
    "dark": "15rem"
  },
  {
    "name": "--ui-container-width-md",
    "layer": "semantic",
    "light": "20rem",
    "dark": "20rem"
  },
  {
    "name": "--ui-container-width-lg",
    "layer": "semantic",
    "light": "24rem",
    "dark": "24rem"
  },
  {
    "name": "--ui-container-width-xl",
    "layer": "semantic",
    "light": "25rem",
    "dark": "25rem"
  },
  {
    "name": "--ui-container-width-2xl",
    "layer": "semantic",
    "light": "35rem",
    "dark": "35rem"
  },
  {
    "name": "--ui-container-width-3xl",
    "layer": "semantic",
    "light": "50rem",
    "dark": "50rem"
  },
  {
    "name": "--ui-media-size-sm",
    "layer": "semantic",
    "light": "1.5rem",
    "dark": "1.5rem"
  },
  {
    "name": "--ui-media-size-md",
    "layer": "semantic",
    "light": "2rem",
    "dark": "2rem"
  },
  {
    "name": "--ui-media-size-lg",
    "layer": "semantic",
    "light": "2.5rem",
    "dark": "2.5rem"
  },
  {
    "name": "--ui-media-size-xl",
    "layer": "semantic",
    "light": "3rem",
    "dark": "3rem"
  },
  {
    "name": "--ui-panel-max-height",
    "layer": "semantic",
    "light": "18rem",
    "dark": "18rem"
  },
  {
    "name": "--ui-em-1",
    "layer": "semantic",
    "light": "1em",
    "dark": "1em"
  },
  {
    "name": "--ui-em-5",
    "layer": "semantic",
    "light": "5em",
    "dark": "5em"
  },
  {
    "name": "--ui-em-6",
    "layer": "semantic",
    "light": "6em",
    "dark": "6em"
  },
  {
    "name": "--ui-em-0-8",
    "layer": "semantic",
    "light": "0.8em",
    "dark": "0.8em"
  },
  {
    "name": "--ui-em-2-5",
    "layer": "semantic",
    "light": "2.5em",
    "dark": "2.5em"
  },
  {
    "name": "--ui-em-0-4",
    "layer": "semantic",
    "light": "0.4em",
    "dark": "0.4em"
  },
  {
    "name": "--ui-z-sticky",
    "layer": "semantic",
    "light": "1100",
    "dark": "1100"
  },
  {
    "name": "--ui-motion-duration-instant",
    "layer": "semantic",
    "light": "50ms",
    "dark": "50ms"
  },
  {
    "name": "--ui-motion-duration-fast",
    "layer": "semantic",
    "light": "120ms",
    "dark": "120ms"
  },
  {
    "name": "--ui-motion-duration-normal",
    "layer": "semantic",
    "light": "200ms",
    "dark": "200ms"
  },
  {
    "name": "--ui-motion-duration-slow",
    "layer": "semantic",
    "light": "320ms",
    "dark": "320ms"
  },
  {
    "name": "--ui-motion-easing-standard",
    "layer": "semantic",
    "light": "cubic-bezier(0.2, 0, 0, 1)",
    "dark": "cubic-bezier(0.2, 0, 0, 1)"
  },
  {
    "name": "--ui-motion-easing-enter",
    "layer": "semantic",
    "light": "cubic-bezier(0, 0, 0.2, 1)",
    "dark": "cubic-bezier(0, 0, 0.2, 1)"
  },
  {
    "name": "--ui-motion-easing-exit",
    "layer": "semantic",
    "light": "cubic-bezier(0.4, 0, 1, 1)",
    "dark": "cubic-bezier(0.4, 0, 1, 1)"
  },
  {
    "name": "--ui-color-bg",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#111723"
  },
  {
    "name": "--ui-color-surface",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#1d2535"
  },
  {
    "name": "--ui-color-surface-subtle",
    "layer": "semantic",
    "light": "#f8f9fb",
    "dark": "#1d2535"
  },
  {
    "name": "--ui-color-surface-muted",
    "layer": "semantic",
    "light": "#f1f3f6",
    "dark": "#2b3549"
  },
  {
    "name": "--ui-color-surface-raised",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#2b3549"
  },
  {
    "name": "--ui-color-surface-hover",
    "layer": "semantic",
    "light": "#f1f3f6",
    "dark": "#364054"
  },
  {
    "name": "--ui-color-surface-active",
    "layer": "semantic",
    "light": "#e4e7ed",
    "dark": "#4a5466"
  },
  {
    "name": "--ui-color-surface-emphasis",
    "layer": "semantic",
    "light": "#cdd2db",
    "dark": "#4a5466"
  },
  {
    "name": "--ui-color-text",
    "layer": "semantic",
    "light": "#1d2535",
    "dark": "#f8f9fb"
  },
  {
    "name": "--ui-color-text-muted",
    "layer": "semantic",
    "light": "#636d7e",
    "dark": "#a7acaf"
  },
  {
    "name": "--ui-color-text-disabled",
    "layer": "semantic",
    "light": "#a7acaf",
    "dark": "#636d7e"
  },
  {
    "name": "--ui-color-text-inverse",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#1d2535"
  },
  {
    "name": "--ui-color-border",
    "layer": "semantic",
    "light": "#e4e7ed",
    "dark": "#4a5466"
  },
  {
    "name": "--ui-color-border-control",
    "layer": "semantic",
    "light": "#848d9d",
    "dark": "#848d9d"
  },
  {
    "name": "--ui-color-border-control-hover",
    "layer": "semantic",
    "light": "#4a5466",
    "dark": "#cdd2db"
  },
  {
    "name": "--ui-color-control-bg",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#1d2535"
  },
  {
    "name": "--ui-color-control-bg-disabled",
    "layer": "semantic",
    "light": "#f1f3f6",
    "dark": "#2b3549"
  },
  {
    "name": "--ui-color-primary",
    "layer": "semantic",
    "light": "#1a74c9",
    "dark": "#4aa3ef"
  },
  {
    "name": "--ui-color-primary-hover",
    "layer": "semantic",
    "light": "#155ea6",
    "dark": "#72b8f2"
  },
  {
    "name": "--ui-color-primary-active",
    "layer": "semantic",
    "light": "#004b9e",
    "dark": "#a8d3f6"
  },
  {
    "name": "--ui-color-primary-contrast",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#111723"
  },
  {
    "name": "--ui-color-primary-subtle",
    "layer": "semantic",
    "light": "#e9f4fc",
    "dark": "#0a2747"
  },
  {
    "name": "--ui-color-primary-text",
    "layer": "semantic",
    "light": "#155ea6",
    "dark": "#72b8f2"
  },
  {
    "name": "--ui-color-danger",
    "layer": "semantic",
    "light": "#dc2626",
    "dark": "#f87171"
  },
  {
    "name": "--ui-color-danger-hover",
    "layer": "semantic",
    "light": "#b91c1c",
    "dark": "#fca5a5"
  },
  {
    "name": "--ui-color-danger-active",
    "layer": "semantic",
    "light": "#991b1b",
    "dark": "#fecaca"
  },
  {
    "name": "--ui-color-danger-contrast",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#111723"
  },
  {
    "name": "--ui-color-danger-subtle",
    "layer": "semantic",
    "light": "#fef2f2",
    "dark": "#450a0a"
  },
  {
    "name": "--ui-color-danger-text",
    "layer": "semantic",
    "light": "#b91c1c",
    "dark": "#fecaca"
  },
  {
    "name": "--ui-color-success",
    "layer": "semantic",
    "light": "#008752",
    "dark": "#3fae7c"
  },
  {
    "name": "--ui-color-success-contrast",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#111723"
  },
  {
    "name": "--ui-color-success-subtle",
    "layer": "semantic",
    "light": "#e8f6ef",
    "dark": "#032819"
  },
  {
    "name": "--ui-color-success-text",
    "layer": "semantic",
    "light": "#006c42",
    "dark": "#5fbf8f"
  },
  {
    "name": "--ui-color-warning",
    "layer": "semantic",
    "light": "#685e1b",
    "dark": "#bfae38"
  },
  {
    "name": "--ui-color-warning-contrast",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#111723"
  },
  {
    "name": "--ui-color-warning-subtle",
    "layer": "semantic",
    "light": "#faf8e8",
    "dark": "#29230a"
  },
  {
    "name": "--ui-color-warning-text",
    "layer": "semantic",
    "light": "#554c1a",
    "dark": "#d4c65a"
  },
  {
    "name": "--ui-color-info",
    "layer": "semantic",
    "light": "#155ea6",
    "dark": "#4aa3ef"
  },
  {
    "name": "--ui-color-info-subtle",
    "layer": "semantic",
    "light": "#e9f4fc",
    "dark": "#0a2747"
  },
  {
    "name": "--ui-color-info-text",
    "layer": "semantic",
    "light": "#155ea6",
    "dark": "#72b8f2"
  },
  {
    "name": "--ui-color-accent-1-bg",
    "layer": "semantic",
    "light": "#d3e9fa",
    "dark": "#0d3d6e"
  },
  {
    "name": "--ui-color-accent-1-text",
    "layer": "semantic",
    "light": "#004b9e",
    "dark": "#a8d3f6"
  },
  {
    "name": "--ui-color-accent-2-bg",
    "layer": "semantic",
    "light": "#c9ebd9",
    "dark": "#07472e"
  },
  {
    "name": "--ui-color-accent-2-text",
    "layer": "semantic",
    "light": "#055636",
    "dark": "#95d6b4"
  },
  {
    "name": "--ui-color-accent-3-bg",
    "layer": "semantic",
    "light": "#f3efc6",
    "dark": "#483f19"
  },
  {
    "name": "--ui-color-accent-3-text",
    "layer": "semantic",
    "light": "#554c1a",
    "dark": "#e6dd8e"
  },
  {
    "name": "--ui-color-accent-4-bg",
    "layer": "semantic",
    "light": "#fee2e2",
    "dark": "#7f1d1d"
  },
  {
    "name": "--ui-color-accent-4-text",
    "layer": "semantic",
    "light": "#991b1b",
    "dark": "#fecaca"
  },
  {
    "name": "--ui-color-accent-5-bg",
    "layer": "semantic",
    "light": "#ede9fe",
    "dark": "#4c1d95"
  },
  {
    "name": "--ui-color-accent-5-text",
    "layer": "semantic",
    "light": "#5b21b6",
    "dark": "#ddd6fe"
  },
  {
    "name": "--ui-color-accent-6-bg",
    "layer": "semantic",
    "light": "#ccfbf1",
    "dark": "#134e4a"
  },
  {
    "name": "--ui-color-accent-6-text",
    "layer": "semantic",
    "light": "#115e59",
    "dark": "#99f6e4"
  },
  {
    "name": "--ui-color-accent-7-bg",
    "layer": "semantic",
    "light": "#ffedd5",
    "dark": "#7c2d12"
  },
  {
    "name": "--ui-color-accent-7-text",
    "layer": "semantic",
    "light": "#9a3412",
    "dark": "#fed7aa"
  },
  {
    "name": "--ui-color-accent-8-bg",
    "layer": "semantic",
    "light": "#fce7f3",
    "dark": "#831843"
  },
  {
    "name": "--ui-color-accent-8-text",
    "layer": "semantic",
    "light": "#9d174d",
    "dark": "#fbcfe8"
  },
  {
    "name": "--ui-color-focus-ring",
    "layer": "semantic",
    "light": "#1a74c9",
    "dark": "#72b8f2"
  },
  {
    "name": "--ui-color-backdrop",
    "layer": "semantic",
    "light": "rgb(15 23 42 / 0.5)",
    "dark": "rgb(0 0 0 / 0.6)"
  },
  {
    "name": "--ui-shadow-sm",
    "layer": "semantic",
    "light": "0 1px 2px 0 rgb(15 23 42 / 0.06)",
    "dark": "0 1px 2px 0 rgb(0 0 0 / 0.4)"
  },
  {
    "name": "--ui-shadow-md",
    "layer": "semantic",
    "light": "0 4px 8px -2px rgb(15 23 42 / 0.10), 0 2px 4px -2px rgb(15 23 42 / 0.06)",
    "dark": "0 4px 8px -2px rgb(0 0 0 / 0.5)"
  },
  {
    "name": "--ui-shadow-lg",
    "layer": "semantic",
    "light": "0 12px 24px -6px rgb(15 23 42 / 0.16), 0 4px 8px -4px rgb(15 23 42 / 0.08)",
    "dark": "0 12px 24px -6px rgb(0 0 0 / 0.6)"
  },
  {
    "name": "--ui-button-radius",
    "layer": "component",
    "light": "var(--ui-radius-control)",
    "dark": "var(--ui-radius-control)"
  },
  {
    "name": "--ui-button-font-weight",
    "layer": "component",
    "light": "var(--ui-font-weight-medium)",
    "dark": "var(--ui-font-weight-medium)"
  },
  {
    "name": "--ui-button-primary-bg",
    "layer": "component",
    "light": "var(--ui-color-primary)",
    "dark": "var(--ui-color-primary)"
  },
  {
    "name": "--ui-button-primary-bg-hover",
    "layer": "component",
    "light": "var(--ui-color-primary-hover)",
    "dark": "var(--ui-color-primary-hover)"
  },
  {
    "name": "--ui-button-primary-bg-active",
    "layer": "component",
    "light": "var(--ui-color-primary-active)",
    "dark": "var(--ui-color-primary-active)"
  },
  {
    "name": "--ui-button-primary-text",
    "layer": "component",
    "light": "var(--ui-color-primary-contrast)",
    "dark": "var(--ui-color-primary-contrast)"
  },
  {
    "name": "--ui-button-primary-border",
    "layer": "component",
    "light": "transparent",
    "dark": "transparent"
  },
  {
    "name": "--ui-button-secondary-bg",
    "layer": "component",
    "light": "var(--ui-color-surface)",
    "dark": "var(--ui-color-surface)"
  },
  {
    "name": "--ui-button-secondary-bg-hover",
    "layer": "component",
    "light": "var(--ui-color-surface-hover)",
    "dark": "var(--ui-color-surface-hover)"
  },
  {
    "name": "--ui-button-secondary-bg-active",
    "layer": "component",
    "light": "var(--ui-color-surface-active)",
    "dark": "var(--ui-color-surface-active)"
  },
  {
    "name": "--ui-button-secondary-text",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-button-secondary-border",
    "layer": "component",
    "light": "var(--ui-color-border-control)",
    "dark": "var(--ui-color-border-control)"
  },
  {
    "name": "--ui-button-ghost-bg",
    "layer": "component",
    "light": "transparent",
    "dark": "transparent"
  },
  {
    "name": "--ui-button-ghost-bg-hover",
    "layer": "component",
    "light": "var(--ui-color-surface-hover)",
    "dark": "var(--ui-color-surface-hover)"
  },
  {
    "name": "--ui-button-ghost-bg-active",
    "layer": "component",
    "light": "var(--ui-color-surface-active)",
    "dark": "var(--ui-color-surface-active)"
  },
  {
    "name": "--ui-button-ghost-text",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-button-ghost-border",
    "layer": "component",
    "light": "transparent",
    "dark": "transparent"
  },
  {
    "name": "--ui-button-danger-bg",
    "layer": "component",
    "light": "var(--ui-color-danger)",
    "dark": "var(--ui-color-danger)"
  },
  {
    "name": "--ui-button-danger-bg-hover",
    "layer": "component",
    "light": "var(--ui-color-danger-hover)",
    "dark": "var(--ui-color-danger-hover)"
  },
  {
    "name": "--ui-button-danger-bg-active",
    "layer": "component",
    "light": "var(--ui-color-danger-active)",
    "dark": "var(--ui-color-danger-active)"
  },
  {
    "name": "--ui-button-danger-text",
    "layer": "component",
    "light": "var(--ui-color-danger-contrast)",
    "dark": "var(--ui-color-danger-contrast)"
  },
  {
    "name": "--ui-button-danger-border",
    "layer": "component",
    "light": "transparent",
    "dark": "transparent"
  },
  {
    "name": "--ui-input-bg",
    "layer": "component",
    "light": "var(--ui-color-control-bg)",
    "dark": "var(--ui-color-control-bg)"
  },
  {
    "name": "--ui-input-bg-disabled",
    "layer": "component",
    "light": "var(--ui-color-control-bg-disabled)",
    "dark": "var(--ui-color-control-bg-disabled)"
  },
  {
    "name": "--ui-input-text",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-input-placeholder",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-input-border",
    "layer": "component",
    "light": "var(--ui-color-border-control)",
    "dark": "var(--ui-color-border-control)"
  },
  {
    "name": "--ui-input-border-hover",
    "layer": "component",
    "light": "var(--ui-color-border-control-hover)",
    "dark": "var(--ui-color-border-control-hover)"
  },
  {
    "name": "--ui-input-border-focus",
    "layer": "component",
    "light": "var(--ui-color-primary)",
    "dark": "var(--ui-color-primary)"
  },
  {
    "name": "--ui-input-border-invalid",
    "layer": "component",
    "light": "var(--ui-color-danger)",
    "dark": "var(--ui-color-danger)"
  },
  {
    "name": "--ui-input-radius",
    "layer": "component",
    "light": "var(--ui-radius-control)",
    "dark": "var(--ui-radius-control)"
  },
  {
    "name": "--ui-form-field-gap",
    "layer": "component",
    "light": "var(--ui-space-2xs)",
    "dark": "var(--ui-space-2xs)"
  },
  {
    "name": "--ui-form-field-label-color",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-form-field-label-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-sm)",
    "dark": "var(--ui-font-size-sm)"
  },
  {
    "name": "--ui-form-field-label-font-weight",
    "layer": "component",
    "light": "var(--ui-font-weight-medium)",
    "dark": "var(--ui-font-weight-medium)"
  },
  {
    "name": "--ui-form-field-hint-color",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-form-field-error-color",
    "layer": "component",
    "light": "var(--ui-color-danger-text)",
    "dark": "var(--ui-color-danger-text)"
  },
  {
    "name": "--ui-form-field-message-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-xs)",
    "dark": "var(--ui-font-size-xs)"
  },
  {
    "name": "--ui-form-field-affix-color",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-checkbox-size",
    "layer": "component",
    "light": "var(--ui-icon-size-sm)",
    "dark": "var(--ui-icon-size-sm)"
  },
  {
    "name": "--ui-checkbox-radius",
    "layer": "component",
    "light": "var(--ui-radius-sm)",
    "dark": "var(--ui-radius-sm)"
  },
  {
    "name": "--ui-checkbox-bg",
    "layer": "component",
    "light": "var(--ui-color-control-bg)",
    "dark": "var(--ui-color-control-bg)"
  },
  {
    "name": "--ui-checkbox-border",
    "layer": "component",
    "light": "var(--ui-color-border-control)",
    "dark": "var(--ui-color-border-control)"
  },
  {
    "name": "--ui-checkbox-checked-bg",
    "layer": "component",
    "light": "var(--ui-color-primary)",
    "dark": "var(--ui-color-primary)"
  },
  {
    "name": "--ui-checkbox-checked-color",
    "layer": "component",
    "light": "var(--ui-color-primary-contrast)",
    "dark": "var(--ui-color-primary-contrast)"
  },
  {
    "name": "--ui-checkbox-invalid-border",
    "layer": "component",
    "light": "var(--ui-color-danger)",
    "dark": "var(--ui-color-danger)"
  },
  {
    "name": "--ui-radio-size",
    "layer": "component",
    "light": "var(--ui-icon-size-sm)",
    "dark": "var(--ui-icon-size-sm)"
  },
  {
    "name": "--ui-radio-bg",
    "layer": "component",
    "light": "var(--ui-color-control-bg)",
    "dark": "var(--ui-color-control-bg)"
  },
  {
    "name": "--ui-radio-border",
    "layer": "component",
    "light": "var(--ui-color-border-control)",
    "dark": "var(--ui-color-border-control)"
  },
  {
    "name": "--ui-radio-checked-color",
    "layer": "component",
    "light": "var(--ui-color-primary)",
    "dark": "var(--ui-color-primary)"
  },
  {
    "name": "--ui-radio-invalid-border",
    "layer": "component",
    "light": "var(--ui-color-danger)",
    "dark": "var(--ui-color-danger)"
  },
  {
    "name": "--ui-switch-track-width",
    "layer": "component",
    "light": "var(--ui-control-height-md)",
    "dark": "var(--ui-control-height-md)"
  },
  {
    "name": "--ui-switch-track-height",
    "layer": "component",
    "light": "var(--ui-icon-size-md)",
    "dark": "var(--ui-icon-size-md)"
  },
  {
    "name": "--ui-switch-track-bg",
    "layer": "component",
    "light": "var(--ui-color-border-control)",
    "dark": "var(--ui-color-border-control)"
  },
  {
    "name": "--ui-switch-track-checked-bg",
    "layer": "component",
    "light": "var(--ui-color-primary)",
    "dark": "var(--ui-color-primary)"
  },
  {
    "name": "--ui-switch-thumb-bg",
    "layer": "component",
    "light": "var(--ui-color-control-bg)",
    "dark": "var(--ui-color-control-bg)"
  },
  {
    "name": "--ui-switch-invalid-outline",
    "layer": "component",
    "light": "var(--ui-color-danger)",
    "dark": "var(--ui-color-danger)"
  },
  {
    "name": "--ui-spinner-track-color",
    "layer": "component",
    "light": "var(--ui-color-border)",
    "dark": "var(--ui-color-border)"
  },
  {
    "name": "--ui-spinner-stroke-width",
    "layer": "component",
    "light": "var(--ui-border-width-strong)",
    "dark": "var(--ui-border-width-strong)"
  },
  {
    "name": "--ui-divider-color",
    "layer": "component",
    "light": "var(--ui-color-border)",
    "dark": "var(--ui-color-border)"
  },
  {
    "name": "--ui-divider-thickness",
    "layer": "component",
    "light": "var(--ui-border-width-default)",
    "dark": "var(--ui-border-width-default)"
  },
  {
    "name": "--ui-divider-label-color",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-divider-label-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-xs)",
    "dark": "var(--ui-font-size-xs)"
  },
  {
    "name": "--ui-divider-label-gap",
    "layer": "component",
    "light": "var(--ui-space-md)",
    "dark": "var(--ui-space-md)"
  },
  {
    "name": "--ui-divider-vertical-min-height",
    "layer": "component",
    "light": "var(--ui-em-1)",
    "dark": "var(--ui-em-1)"
  },
  {
    "name": "--ui-badge-radius",
    "layer": "component",
    "light": "var(--ui-radius-full)",
    "dark": "var(--ui-radius-full)"
  },
  {
    "name": "--ui-badge-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-xs)",
    "dark": "var(--ui-font-size-xs)"
  },
  {
    "name": "--ui-badge-font-size-md",
    "layer": "component",
    "light": "var(--ui-font-size-sm)",
    "dark": "var(--ui-font-size-sm)"
  },
  {
    "name": "--ui-badge-font-size-lg",
    "layer": "component",
    "light": "var(--ui-font-size-md)",
    "dark": "var(--ui-font-size-md)"
  },
  {
    "name": "--ui-badge-dot-size",
    "layer": "component",
    "light": "var(--ui-space-sm)",
    "dark": "var(--ui-space-sm)"
  },
  {
    "name": "--ui-badge-font-weight",
    "layer": "component",
    "light": "var(--ui-font-weight-semibold)",
    "dark": "var(--ui-font-weight-semibold)"
  },
  {
    "name": "--ui-badge-neutral-soft-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-muted)",
    "dark": "var(--ui-color-surface-muted)"
  },
  {
    "name": "--ui-badge-neutral-soft-text",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-badge-neutral-solid-bg",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-badge-neutral-solid-text",
    "layer": "component",
    "light": "var(--ui-color-text-inverse)",
    "dark": "var(--ui-color-text-inverse)"
  },
  {
    "name": "--ui-badge-primary-soft-bg",
    "layer": "component",
    "light": "var(--ui-color-primary-subtle)",
    "dark": "var(--ui-color-primary-subtle)"
  },
  {
    "name": "--ui-badge-primary-soft-text",
    "layer": "component",
    "light": "var(--ui-color-primary-text)",
    "dark": "var(--ui-color-primary-text)"
  },
  {
    "name": "--ui-badge-primary-solid-bg",
    "layer": "component",
    "light": "var(--ui-color-primary)",
    "dark": "var(--ui-color-primary)"
  },
  {
    "name": "--ui-badge-primary-solid-text",
    "layer": "component",
    "light": "var(--ui-color-primary-contrast)",
    "dark": "var(--ui-color-primary-contrast)"
  },
  {
    "name": "--ui-badge-info-soft-bg",
    "layer": "component",
    "light": "var(--ui-color-info-subtle)",
    "dark": "var(--ui-color-info-subtle)"
  },
  {
    "name": "--ui-badge-info-soft-text",
    "layer": "component",
    "light": "var(--ui-color-info-text)",
    "dark": "var(--ui-color-info-text)"
  },
  {
    "name": "--ui-badge-info-solid-bg",
    "layer": "component",
    "light": "var(--ui-color-info)",
    "dark": "var(--ui-color-info)"
  },
  {
    "name": "--ui-badge-info-solid-text",
    "layer": "component",
    "light": "var(--ui-color-primary-contrast)",
    "dark": "var(--ui-color-primary-contrast)"
  },
  {
    "name": "--ui-badge-success-soft-bg",
    "layer": "component",
    "light": "var(--ui-color-success-subtle)",
    "dark": "var(--ui-color-success-subtle)"
  },
  {
    "name": "--ui-badge-success-soft-text",
    "layer": "component",
    "light": "var(--ui-color-success-text)",
    "dark": "var(--ui-color-success-text)"
  },
  {
    "name": "--ui-badge-success-solid-bg",
    "layer": "component",
    "light": "var(--ui-color-success)",
    "dark": "var(--ui-color-success)"
  },
  {
    "name": "--ui-badge-success-solid-text",
    "layer": "component",
    "light": "var(--ui-color-success-contrast)",
    "dark": "var(--ui-color-success-contrast)"
  },
  {
    "name": "--ui-badge-warning-soft-bg",
    "layer": "component",
    "light": "var(--ui-color-warning-subtle)",
    "dark": "var(--ui-color-warning-subtle)"
  },
  {
    "name": "--ui-badge-warning-soft-text",
    "layer": "component",
    "light": "var(--ui-color-warning-text)",
    "dark": "var(--ui-color-warning-text)"
  },
  {
    "name": "--ui-badge-warning-solid-bg",
    "layer": "component",
    "light": "var(--ui-color-warning)",
    "dark": "var(--ui-color-warning)"
  },
  {
    "name": "--ui-badge-warning-solid-text",
    "layer": "component",
    "light": "var(--ui-color-warning-contrast)",
    "dark": "var(--ui-color-warning-contrast)"
  },
  {
    "name": "--ui-badge-danger-soft-bg",
    "layer": "component",
    "light": "var(--ui-color-danger-subtle)",
    "dark": "var(--ui-color-danger-subtle)"
  },
  {
    "name": "--ui-badge-danger-soft-text",
    "layer": "component",
    "light": "var(--ui-color-danger-text)",
    "dark": "var(--ui-color-danger-text)"
  },
  {
    "name": "--ui-badge-danger-solid-bg",
    "layer": "component",
    "light": "var(--ui-color-danger)",
    "dark": "var(--ui-color-danger)"
  },
  {
    "name": "--ui-badge-danger-solid-text",
    "layer": "component",
    "light": "var(--ui-color-danger-contrast)",
    "dark": "var(--ui-color-danger-contrast)"
  },
  {
    "name": "--ui-alert-radius",
    "layer": "component",
    "light": "var(--ui-radius-container)",
    "dark": "var(--ui-radius-container)"
  },
  {
    "name": "--ui-alert-padding-block",
    "layer": "component",
    "light": "var(--ui-space-md)",
    "dark": "var(--ui-space-md)"
  },
  {
    "name": "--ui-alert-padding-inline",
    "layer": "component",
    "light": "var(--ui-space-lg)",
    "dark": "var(--ui-space-lg)"
  },
  {
    "name": "--ui-alert-gap",
    "layer": "component",
    "light": "var(--ui-space-sm)",
    "dark": "var(--ui-space-sm)"
  },
  {
    "name": "--ui-alert-text",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-alert-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-sm)",
    "dark": "var(--ui-font-size-sm)"
  },
  {
    "name": "--ui-alert-title-font-weight",
    "layer": "component",
    "light": "var(--ui-font-weight-semibold)",
    "dark": "var(--ui-font-weight-semibold)"
  },
  {
    "name": "--ui-alert-info-bg",
    "layer": "component",
    "light": "var(--ui-color-info-subtle)",
    "dark": "var(--ui-color-info-subtle)"
  },
  {
    "name": "--ui-alert-info-border",
    "layer": "component",
    "light": "var(--ui-color-info)",
    "dark": "var(--ui-color-info)"
  },
  {
    "name": "--ui-alert-info-icon",
    "layer": "component",
    "light": "var(--ui-color-info-text)",
    "dark": "var(--ui-color-info-text)"
  },
  {
    "name": "--ui-alert-success-bg",
    "layer": "component",
    "light": "var(--ui-color-success-subtle)",
    "dark": "var(--ui-color-success-subtle)"
  },
  {
    "name": "--ui-alert-success-border",
    "layer": "component",
    "light": "var(--ui-color-success)",
    "dark": "var(--ui-color-success)"
  },
  {
    "name": "--ui-alert-success-icon",
    "layer": "component",
    "light": "var(--ui-color-success-text)",
    "dark": "var(--ui-color-success-text)"
  },
  {
    "name": "--ui-alert-warning-bg",
    "layer": "component",
    "light": "var(--ui-color-warning-subtle)",
    "dark": "var(--ui-color-warning-subtle)"
  },
  {
    "name": "--ui-alert-warning-border",
    "layer": "component",
    "light": "var(--ui-color-warning)",
    "dark": "var(--ui-color-warning)"
  },
  {
    "name": "--ui-alert-warning-icon",
    "layer": "component",
    "light": "var(--ui-color-warning-text)",
    "dark": "var(--ui-color-warning-text)"
  },
  {
    "name": "--ui-alert-danger-bg",
    "layer": "component",
    "light": "var(--ui-color-danger-subtle)",
    "dark": "var(--ui-color-danger-subtle)"
  },
  {
    "name": "--ui-alert-danger-border",
    "layer": "component",
    "light": "var(--ui-color-danger)",
    "dark": "var(--ui-color-danger)"
  },
  {
    "name": "--ui-alert-danger-icon",
    "layer": "component",
    "light": "var(--ui-color-danger-text)",
    "dark": "var(--ui-color-danger-text)"
  },
  {
    "name": "--ui-empty-state-gap",
    "layer": "component",
    "light": "var(--ui-space-sm)",
    "dark": "var(--ui-space-sm)"
  },
  {
    "name": "--ui-empty-state-padding-sm",
    "layer": "component",
    "light": "var(--ui-space-lg)",
    "dark": "var(--ui-space-lg)"
  },
  {
    "name": "--ui-empty-state-padding-md",
    "layer": "component",
    "light": "var(--ui-space-2xl)",
    "dark": "var(--ui-space-2xl)"
  },
  {
    "name": "--ui-empty-state-max-width",
    "layer": "component",
    "light": "var(--ui-container-width-lg)",
    "dark": "var(--ui-container-width-lg)"
  },
  {
    "name": "--ui-empty-state-icon-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-muted)",
    "dark": "var(--ui-color-surface-muted)"
  },
  {
    "name": "--ui-empty-state-icon-color",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-empty-state-icon-padding-sm",
    "layer": "component",
    "light": "var(--ui-space-sm)",
    "dark": "var(--ui-space-sm)"
  },
  {
    "name": "--ui-empty-state-icon-padding-md",
    "layer": "component",
    "light": "var(--ui-space-lg)",
    "dark": "var(--ui-space-lg)"
  },
  {
    "name": "--ui-empty-state-icon-size-sm",
    "layer": "component",
    "light": "var(--ui-font-size-2xl)",
    "dark": "var(--ui-font-size-2xl)"
  },
  {
    "name": "--ui-empty-state-icon-size-md",
    "layer": "component",
    "light": "var(--ui-font-size-4xl)",
    "dark": "var(--ui-font-size-4xl)"
  },
  {
    "name": "--ui-empty-state-title-font-size-sm",
    "layer": "component",
    "light": "var(--ui-font-size-md)",
    "dark": "var(--ui-font-size-md)"
  },
  {
    "name": "--ui-empty-state-title-font-size-md",
    "layer": "component",
    "light": "var(--ui-font-size-lg)",
    "dark": "var(--ui-font-size-lg)"
  },
  {
    "name": "--ui-empty-state-title-font-weight",
    "layer": "component",
    "light": "var(--ui-font-weight-semibold)",
    "dark": "var(--ui-font-weight-semibold)"
  },
  {
    "name": "--ui-empty-state-description-color",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-empty-state-description-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-sm)",
    "dark": "var(--ui-font-size-sm)"
  },
  {
    "name": "--ui-progress-track",
    "layer": "component",
    "light": "var(--ui-color-surface-muted)",
    "dark": "var(--ui-color-surface-muted)"
  },
  {
    "name": "--ui-progress-radius",
    "layer": "component",
    "light": "var(--ui-radius-full)",
    "dark": "var(--ui-radius-full)"
  },
  {
    "name": "--ui-progress-height-sm",
    "layer": "component",
    "light": "var(--ui-space-2xs)",
    "dark": "var(--ui-space-2xs)"
  },
  {
    "name": "--ui-progress-height-md",
    "layer": "component",
    "light": "var(--ui-space-sm)",
    "dark": "var(--ui-space-sm)"
  },
  {
    "name": "--ui-progress-primary",
    "layer": "component",
    "light": "var(--ui-color-primary)",
    "dark": "var(--ui-color-primary)"
  },
  {
    "name": "--ui-progress-success",
    "layer": "component",
    "light": "var(--ui-color-success)",
    "dark": "var(--ui-color-success)"
  },
  {
    "name": "--ui-progress-warning",
    "layer": "component",
    "light": "var(--ui-color-warning)",
    "dark": "var(--ui-color-warning)"
  },
  {
    "name": "--ui-progress-danger",
    "layer": "component",
    "light": "var(--ui-color-danger)",
    "dark": "var(--ui-color-danger)"
  },
  {
    "name": "--ui-avatar-radius-square",
    "layer": "component",
    "light": "var(--ui-radius-control)",
    "dark": "var(--ui-radius-control)"
  },
  {
    "name": "--ui-avatar-size-sm",
    "layer": "component",
    "light": "var(--ui-media-size-sm)",
    "dark": "var(--ui-media-size-sm)"
  },
  {
    "name": "--ui-avatar-size-md",
    "layer": "component",
    "light": "var(--ui-media-size-md)",
    "dark": "var(--ui-media-size-md)"
  },
  {
    "name": "--ui-avatar-size-lg",
    "layer": "component",
    "light": "var(--ui-media-size-lg)",
    "dark": "var(--ui-media-size-lg)"
  },
  {
    "name": "--ui-avatar-size-xl",
    "layer": "component",
    "light": "var(--ui-media-size-xl)",
    "dark": "var(--ui-media-size-xl)"
  },
  {
    "name": "--ui-avatar-font-size-sm",
    "layer": "component",
    "light": "var(--ui-font-size-xs)",
    "dark": "var(--ui-font-size-xs)"
  },
  {
    "name": "--ui-avatar-font-size-md",
    "layer": "component",
    "light": "var(--ui-font-size-sm)",
    "dark": "var(--ui-font-size-sm)"
  },
  {
    "name": "--ui-avatar-font-size-lg",
    "layer": "component",
    "light": "var(--ui-font-size-md)",
    "dark": "var(--ui-font-size-md)"
  },
  {
    "name": "--ui-avatar-font-size-xl",
    "layer": "component",
    "light": "var(--ui-font-size-lg)",
    "dark": "var(--ui-font-size-lg)"
  },
  {
    "name": "--ui-avatar-font-weight",
    "layer": "component",
    "light": "var(--ui-font-weight-semibold)",
    "dark": "var(--ui-font-weight-semibold)"
  },
  {
    "name": "--ui-avatar-fallback-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-muted)",
    "dark": "var(--ui-color-surface-muted)"
  },
  {
    "name": "--ui-avatar-fallback-text",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-avatar-group-ring",
    "layer": "component",
    "light": "var(--ui-color-surface)",
    "dark": "var(--ui-color-surface)"
  },
  {
    "name": "--ui-avatar-group-ring-width",
    "layer": "component",
    "light": "var(--ui-border-width-strong)",
    "dark": "var(--ui-border-width-strong)"
  },
  {
    "name": "--ui-avatar-group-overlap",
    "layer": "component",
    "light": "var(--ui-space-xs)",
    "dark": "var(--ui-space-xs)"
  },
  {
    "name": "--ui-avatar-color-1-bg",
    "layer": "component",
    "light": "var(--ui-color-accent-1-bg)",
    "dark": "var(--ui-color-accent-1-bg)"
  },
  {
    "name": "--ui-avatar-color-1-text",
    "layer": "component",
    "light": "var(--ui-color-accent-1-text)",
    "dark": "var(--ui-color-accent-1-text)"
  },
  {
    "name": "--ui-avatar-color-2-bg",
    "layer": "component",
    "light": "var(--ui-color-accent-2-bg)",
    "dark": "var(--ui-color-accent-2-bg)"
  },
  {
    "name": "--ui-avatar-color-2-text",
    "layer": "component",
    "light": "var(--ui-color-accent-2-text)",
    "dark": "var(--ui-color-accent-2-text)"
  },
  {
    "name": "--ui-avatar-color-3-bg",
    "layer": "component",
    "light": "var(--ui-color-accent-3-bg)",
    "dark": "var(--ui-color-accent-3-bg)"
  },
  {
    "name": "--ui-avatar-color-3-text",
    "layer": "component",
    "light": "var(--ui-color-accent-3-text)",
    "dark": "var(--ui-color-accent-3-text)"
  },
  {
    "name": "--ui-avatar-color-4-bg",
    "layer": "component",
    "light": "var(--ui-color-accent-4-bg)",
    "dark": "var(--ui-color-accent-4-bg)"
  },
  {
    "name": "--ui-avatar-color-4-text",
    "layer": "component",
    "light": "var(--ui-color-accent-4-text)",
    "dark": "var(--ui-color-accent-4-text)"
  },
  {
    "name": "--ui-avatar-color-5-bg",
    "layer": "component",
    "light": "var(--ui-color-accent-5-bg)",
    "dark": "var(--ui-color-accent-5-bg)"
  },
  {
    "name": "--ui-avatar-color-5-text",
    "layer": "component",
    "light": "var(--ui-color-accent-5-text)",
    "dark": "var(--ui-color-accent-5-text)"
  },
  {
    "name": "--ui-avatar-color-6-bg",
    "layer": "component",
    "light": "var(--ui-color-accent-6-bg)",
    "dark": "var(--ui-color-accent-6-bg)"
  },
  {
    "name": "--ui-avatar-color-6-text",
    "layer": "component",
    "light": "var(--ui-color-accent-6-text)",
    "dark": "var(--ui-color-accent-6-text)"
  },
  {
    "name": "--ui-avatar-color-7-bg",
    "layer": "component",
    "light": "var(--ui-color-accent-7-bg)",
    "dark": "var(--ui-color-accent-7-bg)"
  },
  {
    "name": "--ui-avatar-color-7-text",
    "layer": "component",
    "light": "var(--ui-color-accent-7-text)",
    "dark": "var(--ui-color-accent-7-text)"
  },
  {
    "name": "--ui-avatar-color-8-bg",
    "layer": "component",
    "light": "var(--ui-color-accent-8-bg)",
    "dark": "var(--ui-color-accent-8-bg)"
  },
  {
    "name": "--ui-avatar-color-8-text",
    "layer": "component",
    "light": "var(--ui-color-accent-8-text)",
    "dark": "var(--ui-color-accent-8-text)"
  },
  {
    "name": "--ui-breadcrumbs-gap",
    "layer": "component",
    "light": "var(--ui-space-xs)",
    "dark": "var(--ui-space-xs)"
  },
  {
    "name": "--ui-breadcrumbs-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-sm)",
    "dark": "var(--ui-font-size-sm)"
  },
  {
    "name": "--ui-breadcrumbs-link",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-breadcrumbs-link-hover",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-breadcrumbs-current",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-breadcrumbs-current-font-weight",
    "layer": "component",
    "light": "var(--ui-font-weight-medium)",
    "dark": "var(--ui-font-weight-medium)"
  },
  {
    "name": "--ui-breadcrumbs-separator",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-breadcrumbs-separator-size",
    "layer": "component",
    "light": "var(--ui-em-0-4)",
    "dark": "var(--ui-em-0-4)"
  },
  {
    "name": "--ui-breadcrumbs-separator-width",
    "layer": "component",
    "light": "var(--ui-border-width-default)",
    "dark": "var(--ui-border-width-default)"
  },
  {
    "name": "--ui-card-bg",
    "layer": "component",
    "light": "var(--ui-color-surface)",
    "dark": "var(--ui-color-surface)"
  },
  {
    "name": "--ui-card-border",
    "layer": "component",
    "light": "var(--ui-color-border)",
    "dark": "var(--ui-color-border)"
  },
  {
    "name": "--ui-card-radius",
    "layer": "component",
    "light": "var(--ui-radius-container)",
    "dark": "var(--ui-radius-container)"
  },
  {
    "name": "--ui-card-shadow",
    "layer": "component",
    "light": "var(--ui-shadow-md)",
    "dark": "var(--ui-shadow-md)"
  },
  {
    "name": "--ui-card-padding-sm",
    "layer": "component",
    "light": "var(--ui-space-md)",
    "dark": "var(--ui-space-md)"
  },
  {
    "name": "--ui-card-padding-md",
    "layer": "component",
    "light": "var(--ui-space-lg)",
    "dark": "var(--ui-space-lg)"
  },
  {
    "name": "--ui-card-padding-lg",
    "layer": "component",
    "light": "var(--ui-space-xl)",
    "dark": "var(--ui-space-xl)"
  },
  {
    "name": "--ui-card-gap",
    "layer": "component",
    "light": "var(--ui-space-md)",
    "dark": "var(--ui-space-md)"
  },
  {
    "name": "--ui-card-title-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-lg)",
    "dark": "var(--ui-font-size-lg)"
  },
  {
    "name": "--ui-card-title-font-weight",
    "layer": "component",
    "light": "var(--ui-font-weight-semibold)",
    "dark": "var(--ui-font-weight-semibold)"
  },
  {
    "name": "--ui-card-subtitle-color",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-tabs-border",
    "layer": "component",
    "light": "var(--ui-color-border)",
    "dark": "var(--ui-color-border)"
  },
  {
    "name": "--ui-tabs-text",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-tabs-text-hover",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-tabs-text-selected",
    "layer": "component",
    "light": "var(--ui-color-primary-text)",
    "dark": "var(--ui-color-primary-text)"
  },
  {
    "name": "--ui-tabs-indicator",
    "layer": "component",
    "light": "var(--ui-color-primary)",
    "dark": "var(--ui-color-primary)"
  },
  {
    "name": "--ui-tabs-indicator-thickness",
    "layer": "component",
    "light": "var(--ui-border-width-strong)",
    "dark": "var(--ui-border-width-strong)"
  },
  {
    "name": "--ui-tabs-height",
    "layer": "component",
    "light": "var(--ui-control-height-lg)",
    "dark": "var(--ui-control-height-lg)"
  },
  {
    "name": "--ui-tabs-padding-inline",
    "layer": "component",
    "light": "var(--ui-space-lg)",
    "dark": "var(--ui-space-lg)"
  },
  {
    "name": "--ui-tabs-gap",
    "layer": "component",
    "light": "var(--ui-space-2xs)",
    "dark": "var(--ui-space-2xs)"
  },
  {
    "name": "--ui-tabs-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-md)",
    "dark": "var(--ui-font-size-md)"
  },
  {
    "name": "--ui-tabs-font-weight",
    "layer": "component",
    "light": "var(--ui-font-weight-medium)",
    "dark": "var(--ui-font-weight-medium)"
  },
  {
    "name": "--ui-tabs-panel-padding",
    "layer": "component",
    "light": "var(--ui-space-lg)",
    "dark": "var(--ui-space-lg)"
  },
  {
    "name": "--ui-tooltip-bg",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-tooltip-text",
    "layer": "component",
    "light": "var(--ui-color-text-inverse)",
    "dark": "var(--ui-color-text-inverse)"
  },
  {
    "name": "--ui-tooltip-radius",
    "layer": "component",
    "light": "var(--ui-radius-sm)",
    "dark": "var(--ui-radius-sm)"
  },
  {
    "name": "--ui-tooltip-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-xs)",
    "dark": "var(--ui-font-size-xs)"
  },
  {
    "name": "--ui-tooltip-max-width",
    "layer": "component",
    "light": "var(--ui-container-width-sm)",
    "dark": "var(--ui-container-width-sm)"
  },
  {
    "name": "--ui-tooltip-offset",
    "layer": "component",
    "light": "var(--ui-space-xs)",
    "dark": "var(--ui-space-xs)"
  },
  {
    "name": "--ui-tooltip-viewport-margin",
    "layer": "component",
    "light": "var(--ui-space-sm)",
    "dark": "var(--ui-space-sm)"
  },
  {
    "name": "--ui-popover-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-raised)",
    "dark": "var(--ui-color-surface-raised)"
  },
  {
    "name": "--ui-popover-border",
    "layer": "component",
    "light": "var(--ui-color-surface-active)",
    "dark": "var(--ui-color-surface-active)"
  },
  {
    "name": "--ui-popover-radius",
    "layer": "component",
    "light": "var(--ui-radius-container)",
    "dark": "var(--ui-radius-container)"
  },
  {
    "name": "--ui-popover-shadow",
    "layer": "component",
    "light": "var(--ui-shadow-md)",
    "dark": "var(--ui-shadow-md)"
  },
  {
    "name": "--ui-popover-padding",
    "layer": "component",
    "light": "var(--ui-space-lg)",
    "dark": "var(--ui-space-lg)"
  },
  {
    "name": "--ui-popover-max-width",
    "layer": "component",
    "light": "var(--ui-container-width-md)",
    "dark": "var(--ui-container-width-md)"
  },
  {
    "name": "--ui-popover-offset",
    "layer": "component",
    "light": "var(--ui-space-xs)",
    "dark": "var(--ui-space-xs)"
  },
  {
    "name": "--ui-popover-viewport-margin",
    "layer": "component",
    "light": "var(--ui-space-sm)",
    "dark": "var(--ui-space-sm)"
  },
  {
    "name": "--ui-dialog-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-raised)",
    "dark": "var(--ui-color-surface-raised)"
  },
  {
    "name": "--ui-dialog-radius",
    "layer": "component",
    "light": "var(--ui-radius-container)",
    "dark": "var(--ui-radius-container)"
  },
  {
    "name": "--ui-dialog-shadow",
    "layer": "component",
    "light": "var(--ui-shadow-lg)",
    "dark": "var(--ui-shadow-lg)"
  },
  {
    "name": "--ui-dialog-backdrop",
    "layer": "component",
    "light": "var(--ui-color-backdrop)",
    "dark": "var(--ui-color-backdrop)"
  },
  {
    "name": "--ui-dialog-padding",
    "layer": "component",
    "light": "var(--ui-space-xl)",
    "dark": "var(--ui-space-xl)"
  },
  {
    "name": "--ui-dialog-gap",
    "layer": "component",
    "light": "var(--ui-space-lg)",
    "dark": "var(--ui-space-lg)"
  },
  {
    "name": "--ui-dialog-width-sm",
    "layer": "component",
    "light": "var(--ui-container-width-xl)",
    "dark": "var(--ui-container-width-xl)"
  },
  {
    "name": "--ui-dialog-width-md",
    "layer": "component",
    "light": "var(--ui-container-width-2xl)",
    "dark": "var(--ui-container-width-2xl)"
  },
  {
    "name": "--ui-dialog-width-lg",
    "layer": "component",
    "light": "var(--ui-container-width-3xl)",
    "dark": "var(--ui-container-width-3xl)"
  },
  {
    "name": "--ui-dialog-title-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-xl)",
    "dark": "var(--ui-font-size-xl)"
  },
  {
    "name": "--ui-dialog-title-font-weight",
    "layer": "component",
    "light": "var(--ui-font-weight-semibold)",
    "dark": "var(--ui-font-weight-semibold)"
  },
  {
    "name": "--ui-drawer-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-raised)",
    "dark": "var(--ui-color-surface-raised)"
  },
  {
    "name": "--ui-drawer-shadow",
    "layer": "component",
    "light": "var(--ui-shadow-lg)",
    "dark": "var(--ui-shadow-lg)"
  },
  {
    "name": "--ui-drawer-width-sm",
    "layer": "component",
    "light": "var(--ui-container-width-md)",
    "dark": "var(--ui-container-width-md)"
  },
  {
    "name": "--ui-drawer-width-md",
    "layer": "component",
    "light": "var(--ui-container-width-lg)",
    "dark": "var(--ui-container-width-lg)"
  },
  {
    "name": "--ui-drawer-width-lg",
    "layer": "component",
    "light": "var(--ui-container-width-2xl)",
    "dark": "var(--ui-container-width-2xl)"
  },
  {
    "name": "--ui-toast-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-raised)",
    "dark": "var(--ui-color-surface-raised)"
  },
  {
    "name": "--ui-toast-text",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-toast-border",
    "layer": "component",
    "light": "var(--ui-color-border)",
    "dark": "var(--ui-color-border)"
  },
  {
    "name": "--ui-toast-radius",
    "layer": "component",
    "light": "var(--ui-radius-container)",
    "dark": "var(--ui-radius-container)"
  },
  {
    "name": "--ui-toast-shadow",
    "layer": "component",
    "light": "var(--ui-shadow-lg)",
    "dark": "var(--ui-shadow-lg)"
  },
  {
    "name": "--ui-toast-width",
    "layer": "component",
    "light": "var(--ui-container-width-lg)",
    "dark": "var(--ui-container-width-lg)"
  },
  {
    "name": "--ui-toast-gap",
    "layer": "component",
    "light": "var(--ui-space-sm)",
    "dark": "var(--ui-space-sm)"
  },
  {
    "name": "--ui-toast-offset",
    "layer": "component",
    "light": "var(--ui-space-lg)",
    "dark": "var(--ui-space-lg)"
  },
  {
    "name": "--ui-toast-info-accent",
    "layer": "component",
    "light": "var(--ui-color-info)",
    "dark": "var(--ui-color-info)"
  },
  {
    "name": "--ui-toast-success-accent",
    "layer": "component",
    "light": "var(--ui-color-success)",
    "dark": "var(--ui-color-success)"
  },
  {
    "name": "--ui-toast-warning-accent",
    "layer": "component",
    "light": "var(--ui-color-warning)",
    "dark": "var(--ui-color-warning)"
  },
  {
    "name": "--ui-toast-danger-accent",
    "layer": "component",
    "light": "var(--ui-color-danger)",
    "dark": "var(--ui-color-danger)"
  },
  {
    "name": "--ui-select-panel-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-raised)",
    "dark": "var(--ui-color-surface-raised)"
  },
  {
    "name": "--ui-select-panel-border",
    "layer": "component",
    "light": "var(--ui-color-border)",
    "dark": "var(--ui-color-border)"
  },
  {
    "name": "--ui-select-panel-radius",
    "layer": "component",
    "light": "var(--ui-radius-control)",
    "dark": "var(--ui-radius-control)"
  },
  {
    "name": "--ui-select-panel-shadow",
    "layer": "component",
    "light": "var(--ui-shadow-md)",
    "dark": "var(--ui-shadow-md)"
  },
  {
    "name": "--ui-select-panel-max-height",
    "layer": "component",
    "light": "var(--ui-panel-max-height)",
    "dark": "var(--ui-panel-max-height)"
  },
  {
    "name": "--ui-select-option-height",
    "layer": "component",
    "light": "var(--ui-control-height-sm)",
    "dark": "var(--ui-control-height-sm)"
  },
  {
    "name": "--ui-select-option-hover-bg",
    "layer": "component",
    "light": "var(--ui-color-primary-subtle)",
    "dark": "var(--ui-color-primary-subtle)"
  },
  {
    "name": "--ui-select-option-active-bg",
    "layer": "component",
    "light": "var(--ui-color-primary-subtle)",
    "dark": "var(--ui-color-primary-subtle)"
  },
  {
    "name": "--ui-select-option-selected-text",
    "layer": "component",
    "light": "var(--ui-color-primary-text)",
    "dark": "var(--ui-color-primary-text)"
  },
  {
    "name": "--ui-skeleton-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-emphasis)",
    "dark": "var(--ui-color-surface-emphasis)"
  },
  {
    "name": "--ui-skeleton-highlight",
    "layer": "component",
    "light": "var(--ui-color-surface-muted)",
    "dark": "var(--ui-color-surface-muted)"
  },
  {
    "name": "--ui-skeleton-radius-text",
    "layer": "component",
    "light": "var(--ui-radius-sm)",
    "dark": "var(--ui-radius-sm)"
  },
  {
    "name": "--ui-skeleton-radius-rect",
    "layer": "component",
    "light": "var(--ui-radius-control)",
    "dark": "var(--ui-radius-control)"
  },
  {
    "name": "--ui-skeleton-line-gap",
    "layer": "component",
    "light": "var(--ui-space-xs)",
    "dark": "var(--ui-space-xs)"
  },
  {
    "name": "--ui-skeleton-text-height",
    "layer": "component",
    "light": "var(--ui-em-0-8)",
    "dark": "var(--ui-em-0-8)"
  },
  {
    "name": "--ui-skeleton-rect-height",
    "layer": "component",
    "light": "var(--ui-em-6)",
    "dark": "var(--ui-em-6)"
  },
  {
    "name": "--ui-skeleton-circle-size",
    "layer": "component",
    "light": "var(--ui-em-2-5)",
    "dark": "var(--ui-em-2-5)"
  },
  {
    "name": "--ui-accordion-bg",
    "layer": "component",
    "light": "var(--ui-color-surface)",
    "dark": "var(--ui-color-surface)"
  },
  {
    "name": "--ui-accordion-border",
    "layer": "component",
    "light": "var(--ui-color-border)",
    "dark": "var(--ui-color-border)"
  },
  {
    "name": "--ui-accordion-radius",
    "layer": "component",
    "light": "var(--ui-radius-container)",
    "dark": "var(--ui-radius-container)"
  },
  {
    "name": "--ui-accordion-header-text",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-accordion-header-hover-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-hover)",
    "dark": "var(--ui-color-surface-hover)"
  },
  {
    "name": "--ui-accordion-header-padding-block",
    "layer": "component",
    "light": "var(--ui-space-md)",
    "dark": "var(--ui-space-md)"
  },
  {
    "name": "--ui-accordion-header-padding-inline",
    "layer": "component",
    "light": "var(--ui-space-lg)",
    "dark": "var(--ui-space-lg)"
  },
  {
    "name": "--ui-accordion-header-gap",
    "layer": "component",
    "light": "var(--ui-space-sm)",
    "dark": "var(--ui-space-sm)"
  },
  {
    "name": "--ui-accordion-header-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-md)",
    "dark": "var(--ui-font-size-md)"
  },
  {
    "name": "--ui-accordion-header-font-weight",
    "layer": "component",
    "light": "var(--ui-font-weight-semibold)",
    "dark": "var(--ui-font-weight-semibold)"
  },
  {
    "name": "--ui-accordion-icon-color",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-accordion-panel-padding-block",
    "layer": "component",
    "light": "var(--ui-space-md)",
    "dark": "var(--ui-space-md)"
  },
  {
    "name": "--ui-accordion-panel-padding-inline",
    "layer": "component",
    "light": "var(--ui-space-lg)",
    "dark": "var(--ui-space-lg)"
  },
  {
    "name": "--ui-menu-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-raised)",
    "dark": "var(--ui-color-surface-raised)"
  },
  {
    "name": "--ui-menu-border",
    "layer": "component",
    "light": "var(--ui-color-surface-active)",
    "dark": "var(--ui-color-surface-active)"
  },
  {
    "name": "--ui-menu-divider",
    "layer": "component",
    "light": "var(--ui-color-surface-active)",
    "dark": "var(--ui-color-surface-active)"
  },
  {
    "name": "--ui-menu-radius",
    "layer": "component",
    "light": "var(--ui-radius-control)",
    "dark": "var(--ui-radius-control)"
  },
  {
    "name": "--ui-menu-shadow",
    "layer": "component",
    "light": "var(--ui-shadow-md)",
    "dark": "var(--ui-shadow-md)"
  },
  {
    "name": "--ui-menu-padding-block",
    "layer": "component",
    "light": "var(--ui-space-2xs)",
    "dark": "var(--ui-space-2xs)"
  },
  {
    "name": "--ui-menu-min-width",
    "layer": "component",
    "light": "var(--ui-container-width-xs)",
    "dark": "var(--ui-container-width-xs)"
  },
  {
    "name": "--ui-menu-max-width",
    "layer": "component",
    "light": "var(--ui-container-width-md)",
    "dark": "var(--ui-container-width-md)"
  },
  {
    "name": "--ui-menu-max-height",
    "layer": "component",
    "light": "var(--ui-panel-max-height)",
    "dark": "var(--ui-panel-max-height)"
  },
  {
    "name": "--ui-menu-item-height",
    "layer": "component",
    "light": "var(--ui-control-height-md)",
    "dark": "var(--ui-control-height-md)"
  },
  {
    "name": "--ui-menu-item-padding-inline",
    "layer": "component",
    "light": "var(--ui-space-md)",
    "dark": "var(--ui-space-md)"
  },
  {
    "name": "--ui-menu-item-gap",
    "layer": "component",
    "light": "var(--ui-space-sm)",
    "dark": "var(--ui-space-sm)"
  },
  {
    "name": "--ui-menu-item-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-sm)",
    "dark": "var(--ui-font-size-sm)"
  },
  {
    "name": "--ui-menu-item-text",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-menu-item-hover-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-active)",
    "dark": "var(--ui-color-surface-active)"
  },
  {
    "name": "--ui-menu-item-icon-color",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-menu-item-danger-text",
    "layer": "component",
    "light": "var(--ui-color-danger-text)",
    "dark": "var(--ui-color-danger-text)"
  },
  {
    "name": "--ui-menu-item-danger-hover-bg",
    "layer": "component",
    "light": "var(--ui-color-danger-subtle)",
    "dark": "var(--ui-color-danger-subtle)"
  },
  {
    "name": "--ui-pagination-gap",
    "layer": "component",
    "light": "var(--ui-space-lg)",
    "dark": "var(--ui-space-lg)"
  },
  {
    "name": "--ui-pagination-button-gap",
    "layer": "component",
    "light": "var(--ui-space-2xs)",
    "dark": "var(--ui-space-2xs)"
  },
  {
    "name": "--ui-pagination-page-size",
    "layer": "component",
    "light": "var(--ui-control-height-sm)",
    "dark": "var(--ui-control-height-sm)"
  },
  {
    "name": "--ui-pagination-page-radius",
    "layer": "component",
    "light": "var(--ui-radius-control)",
    "dark": "var(--ui-radius-control)"
  },
  {
    "name": "--ui-pagination-page-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-sm)",
    "dark": "var(--ui-font-size-sm)"
  },
  {
    "name": "--ui-pagination-page-text",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-pagination-page-hover-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-hover)",
    "dark": "var(--ui-color-surface-hover)"
  },
  {
    "name": "--ui-pagination-page-current-bg",
    "layer": "component",
    "light": "var(--ui-color-primary)",
    "dark": "var(--ui-color-primary)"
  },
  {
    "name": "--ui-pagination-page-current-text",
    "layer": "component",
    "light": "var(--ui-color-primary-contrast)",
    "dark": "var(--ui-color-primary-contrast)"
  },
  {
    "name": "--ui-pagination-summary-text",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-pagination-summary-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-sm)",
    "dark": "var(--ui-font-size-sm)"
  },
  {
    "name": "--ui-pagination-size-min-width",
    "layer": "component",
    "light": "var(--ui-em-5)",
    "dark": "var(--ui-em-5)"
  },
  {
    "name": "--ui-table-bg",
    "layer": "component",
    "light": "var(--ui-color-surface)",
    "dark": "var(--ui-color-surface)"
  },
  {
    "name": "--ui-table-border",
    "layer": "component",
    "light": "var(--ui-color-border)",
    "dark": "var(--ui-color-border)"
  },
  {
    "name": "--ui-table-text",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-table-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-sm)",
    "dark": "var(--ui-font-size-sm)"
  },
  {
    "name": "--ui-table-header-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-muted)",
    "dark": "var(--ui-color-surface-muted)"
  },
  {
    "name": "--ui-table-header-text",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-table-header-font-weight",
    "layer": "component",
    "light": "var(--ui-font-weight-semibold)",
    "dark": "var(--ui-font-weight-semibold)"
  },
  {
    "name": "--ui-table-row-hover-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-hover)",
    "dark": "var(--ui-color-surface-hover)"
  },
  {
    "name": "--ui-table-cell-padding-inline",
    "layer": "component",
    "light": "var(--ui-space-md)",
    "dark": "var(--ui-space-md)"
  },
  {
    "name": "--ui-table-cell-padding-block",
    "layer": "component",
    "light": "var(--ui-space-md)",
    "dark": "var(--ui-space-md)"
  },
  {
    "name": "--ui-table-cell-padding-block-compact",
    "layer": "component",
    "light": "var(--ui-space-xs)",
    "dark": "var(--ui-space-xs)"
  },
  {
    "name": "--ui-table-message-padding",
    "layer": "component",
    "light": "var(--ui-space-2xl)",
    "dark": "var(--ui-space-2xl)"
  },
  {
    "name": "--ui-table-message-text",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-table-sort-icon",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-table-sort-icon-active",
    "layer": "component",
    "light": "var(--ui-color-primary-text)",
    "dark": "var(--ui-color-primary-text)"
  },
  {
    "name": "--ui-calendar-cell-size",
    "layer": "component",
    "light": "var(--ui-control-height-md)",
    "dark": "var(--ui-control-height-md)"
  },
  {
    "name": "--ui-calendar-cell-radius",
    "layer": "component",
    "light": "var(--ui-radius-full)",
    "dark": "var(--ui-radius-full)"
  },
  {
    "name": "--ui-calendar-gap",
    "layer": "component",
    "light": "var(--ui-space-3xs)",
    "dark": "var(--ui-space-3xs)"
  },
  {
    "name": "--ui-calendar-cell-hover-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-active)",
    "dark": "var(--ui-color-surface-active)"
  },
  {
    "name": "--ui-calendar-selected-bg",
    "layer": "component",
    "light": "var(--ui-color-primary)",
    "dark": "var(--ui-color-primary)"
  },
  {
    "name": "--ui-calendar-selected-text",
    "layer": "component",
    "light": "var(--ui-color-primary-contrast)",
    "dark": "var(--ui-color-primary-contrast)"
  },
  {
    "name": "--ui-calendar-today-border",
    "layer": "component",
    "light": "var(--ui-color-primary)",
    "dark": "var(--ui-color-primary)"
  },
  {
    "name": "--ui-calendar-weekday-text",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-calendar-weekday-height",
    "layer": "component",
    "light": "var(--ui-control-height-sm)",
    "dark": "var(--ui-control-height-sm)"
  },
  {
    "name": "--ui-calendar-title-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-md)",
    "dark": "var(--ui-font-size-md)"
  },
  {
    "name": "--ui-calendar-title-font-weight",
    "layer": "component",
    "light": "var(--ui-font-weight-semibold)",
    "dark": "var(--ui-font-weight-semibold)"
  },
  {
    "name": "--ui-datepicker-panel-bg",
    "layer": "component",
    "light": "var(--ui-color-surface-raised)",
    "dark": "var(--ui-color-surface-raised)"
  },
  {
    "name": "--ui-datepicker-panel-border",
    "layer": "component",
    "light": "var(--ui-color-surface-active)",
    "dark": "var(--ui-color-surface-active)"
  },
  {
    "name": "--ui-datepicker-panel-radius",
    "layer": "component",
    "light": "var(--ui-radius-container)",
    "dark": "var(--ui-radius-container)"
  },
  {
    "name": "--ui-datepicker-panel-shadow",
    "layer": "component",
    "light": "var(--ui-shadow-md)",
    "dark": "var(--ui-shadow-md)"
  },
  {
    "name": "--ui-datepicker-panel-padding",
    "layer": "component",
    "light": "var(--ui-space-md)",
    "dark": "var(--ui-space-md)"
  }
];
