/* Generated by tokens/build-tokens.ts from tokens.json. Do not edit by hand. */
export interface UiTokenDoc {
  name: string;
  layer: 'primitive' | 'semantic' | 'component';
  light: string;
  dark: string;
}

export const UI_TOKENS: readonly UiTokenDoc[] = [
  {
    "name": "--ui-ref-color-white",
    "layer": "primitive",
    "light": "#ffffff",
    "dark": "#ffffff"
  },
  {
    "name": "--ui-ref-color-black",
    "layer": "primitive",
    "light": "#000000",
    "dark": "#000000"
  },
  {
    "name": "--ui-ref-color-red-50",
    "layer": "primitive",
    "light": "#fef2f2",
    "dark": "#fef2f2"
  },
  {
    "name": "--ui-ref-color-red-100",
    "layer": "primitive",
    "light": "#fee2e2",
    "dark": "#fee2e2"
  },
  {
    "name": "--ui-ref-color-red-200",
    "layer": "primitive",
    "light": "#fecaca",
    "dark": "#fecaca"
  },
  {
    "name": "--ui-ref-color-red-300",
    "layer": "primitive",
    "light": "#fca5a5",
    "dark": "#fca5a5"
  },
  {
    "name": "--ui-ref-color-red-400",
    "layer": "primitive",
    "light": "#f87171",
    "dark": "#f87171"
  },
  {
    "name": "--ui-ref-color-red-500",
    "layer": "primitive",
    "light": "#ef4444",
    "dark": "#ef4444"
  },
  {
    "name": "--ui-ref-color-red-600",
    "layer": "primitive",
    "light": "#dc2626",
    "dark": "#dc2626"
  },
  {
    "name": "--ui-ref-color-red-700",
    "layer": "primitive",
    "light": "#b91c1c",
    "dark": "#b91c1c"
  },
  {
    "name": "--ui-ref-color-red-800",
    "layer": "primitive",
    "light": "#991b1b",
    "dark": "#991b1b"
  },
  {
    "name": "--ui-ref-color-red-900",
    "layer": "primitive",
    "light": "#7f1d1d",
    "dark": "#7f1d1d"
  },
  {
    "name": "--ui-ref-color-red-950",
    "layer": "primitive",
    "light": "#450a0a",
    "dark": "#450a0a"
  },
  {
    "name": "--ui-ref-color-green-50",
    "layer": "primitive",
    "light": "#e8f6ef",
    "dark": "#e8f6ef"
  },
  {
    "name": "--ui-ref-color-green-100",
    "layer": "primitive",
    "light": "#c9ebd9",
    "dark": "#c9ebd9"
  },
  {
    "name": "--ui-ref-color-green-200",
    "layer": "primitive",
    "light": "#95d6b4",
    "dark": "#95d6b4"
  },
  {
    "name": "--ui-ref-color-green-300",
    "layer": "primitive",
    "light": "#5fbf8f",
    "dark": "#5fbf8f"
  },
  {
    "name": "--ui-ref-color-green-400",
    "layer": "primitive",
    "light": "#3fae7c",
    "dark": "#3fae7c"
  },
  {
    "name": "--ui-ref-color-green-500",
    "layer": "primitive",
    "light": "#0f9a61",
    "dark": "#0f9a61"
  },
  {
    "name": "--ui-ref-color-green-600",
    "layer": "primitive",
    "light": "#008752",
    "dark": "#008752"
  },
  {
    "name": "--ui-ref-color-green-700",
    "layer": "primitive",
    "light": "#006c42",
    "dark": "#006c42"
  },
  {
    "name": "--ui-ref-color-green-800",
    "layer": "primitive",
    "light": "#055636",
    "dark": "#055636"
  },
  {
    "name": "--ui-ref-color-green-900",
    "layer": "primitive",
    "light": "#07472e",
    "dark": "#07472e"
  },
  {
    "name": "--ui-ref-color-green-950",
    "layer": "primitive",
    "light": "#032819",
    "dark": "#032819"
  },
  {
    "name": "--ui-ref-color-brand-50",
    "layer": "primitive",
    "light": "#e9f4fc",
    "dark": "#e9f4fc"
  },
  {
    "name": "--ui-ref-color-brand-100",
    "layer": "primitive",
    "light": "#d3e9fa",
    "dark": "#d3e9fa"
  },
  {
    "name": "--ui-ref-color-brand-200",
    "layer": "primitive",
    "light": "#a8d3f6",
    "dark": "#a8d3f6"
  },
  {
    "name": "--ui-ref-color-brand-300",
    "layer": "primitive",
    "light": "#72b8f2",
    "dark": "#72b8f2"
  },
  {
    "name": "--ui-ref-color-brand-400",
    "layer": "primitive",
    "light": "#4aa3ef",
    "dark": "#4aa3ef"
  },
  {
    "name": "--ui-ref-color-brand-500",
    "layer": "primitive",
    "light": "#2490ed",
    "dark": "#2490ed"
  },
  {
    "name": "--ui-ref-color-brand-600",
    "layer": "primitive",
    "light": "#1a74c9",
    "dark": "#1a74c9"
  },
  {
    "name": "--ui-ref-color-brand-700",
    "layer": "primitive",
    "light": "#155ea6",
    "dark": "#155ea6"
  },
  {
    "name": "--ui-ref-color-brand-800",
    "layer": "primitive",
    "light": "#004b9e",
    "dark": "#004b9e"
  },
  {
    "name": "--ui-ref-color-brand-900",
    "layer": "primitive",
    "light": "#0d3d6e",
    "dark": "#0d3d6e"
  },
  {
    "name": "--ui-ref-color-brand-950",
    "layer": "primitive",
    "light": "#0a2747",
    "dark": "#0a2747"
  },
  {
    "name": "--ui-ref-color-gray-50",
    "layer": "primitive",
    "light": "#f8f9fb",
    "dark": "#f8f9fb"
  },
  {
    "name": "--ui-ref-color-gray-100",
    "layer": "primitive",
    "light": "#f1f3f6",
    "dark": "#f1f3f6"
  },
  {
    "name": "--ui-ref-color-gray-200",
    "layer": "primitive",
    "light": "#e4e7ed",
    "dark": "#e4e7ed"
  },
  {
    "name": "--ui-ref-color-gray-300",
    "layer": "primitive",
    "light": "#cdd2db",
    "dark": "#cdd2db"
  },
  {
    "name": "--ui-ref-color-gray-400",
    "layer": "primitive",
    "light": "#a7acaf",
    "dark": "#a7acaf"
  },
  {
    "name": "--ui-ref-color-gray-500",
    "layer": "primitive",
    "light": "#848d9d",
    "dark": "#848d9d"
  },
  {
    "name": "--ui-ref-color-gray-600",
    "layer": "primitive",
    "light": "#636d7e",
    "dark": "#636d7e"
  },
  {
    "name": "--ui-ref-color-gray-700",
    "layer": "primitive",
    "light": "#4a5466",
    "dark": "#4a5466"
  },
  {
    "name": "--ui-ref-color-gray-800",
    "layer": "primitive",
    "light": "#2b3549",
    "dark": "#2b3549"
  },
  {
    "name": "--ui-ref-color-gray-900",
    "layer": "primitive",
    "light": "#1d2535",
    "dark": "#1d2535"
  },
  {
    "name": "--ui-ref-color-gray-950",
    "layer": "primitive",
    "light": "#111723",
    "dark": "#111723"
  },
  {
    "name": "--ui-ref-color-olive-50",
    "layer": "primitive",
    "light": "#faf8e8",
    "dark": "#faf8e8"
  },
  {
    "name": "--ui-ref-color-olive-100",
    "layer": "primitive",
    "light": "#f3efc6",
    "dark": "#f3efc6"
  },
  {
    "name": "--ui-ref-color-olive-200",
    "layer": "primitive",
    "light": "#e6dd8e",
    "dark": "#e6dd8e"
  },
  {
    "name": "--ui-ref-color-olive-300",
    "layer": "primitive",
    "light": "#d4c65a",
    "dark": "#d4c65a"
  },
  {
    "name": "--ui-ref-color-olive-400",
    "layer": "primitive",
    "light": "#bfae38",
    "dark": "#bfae38"
  },
  {
    "name": "--ui-ref-color-olive-500",
    "layer": "primitive",
    "light": "#a19329",
    "dark": "#a19329"
  },
  {
    "name": "--ui-ref-color-olive-600",
    "layer": "primitive",
    "light": "#857820",
    "dark": "#857820"
  },
  {
    "name": "--ui-ref-color-olive-700",
    "layer": "primitive",
    "light": "#685e1b",
    "dark": "#685e1b"
  },
  {
    "name": "--ui-ref-color-olive-800",
    "layer": "primitive",
    "light": "#554c1a",
    "dark": "#554c1a"
  },
  {
    "name": "--ui-ref-color-olive-900",
    "layer": "primitive",
    "light": "#483f19",
    "dark": "#483f19"
  },
  {
    "name": "--ui-ref-color-olive-950",
    "layer": "primitive",
    "light": "#29230a",
    "dark": "#29230a"
  },
  {
    "name": "--ui-ref-space-0",
    "layer": "primitive",
    "light": "0",
    "dark": "0"
  },
  {
    "name": "--ui-ref-space-1",
    "layer": "primitive",
    "light": "0.25rem",
    "dark": "0.25rem"
  },
  {
    "name": "--ui-ref-space-2",
    "layer": "primitive",
    "light": "0.5rem",
    "dark": "0.5rem"
  },
  {
    "name": "--ui-ref-space-3",
    "layer": "primitive",
    "light": "0.75rem",
    "dark": "0.75rem"
  },
  {
    "name": "--ui-ref-space-4",
    "layer": "primitive",
    "light": "1rem",
    "dark": "1rem"
  },
  {
    "name": "--ui-ref-space-5",
    "layer": "primitive",
    "light": "1.25rem",
    "dark": "1.25rem"
  },
  {
    "name": "--ui-ref-space-6",
    "layer": "primitive",
    "light": "1.5rem",
    "dark": "1.5rem"
  },
  {
    "name": "--ui-ref-space-8",
    "layer": "primitive",
    "light": "2rem",
    "dark": "2rem"
  },
  {
    "name": "--ui-ref-space-9",
    "layer": "primitive",
    "light": "2.25rem",
    "dark": "2.25rem"
  },
  {
    "name": "--ui-ref-space-10",
    "layer": "primitive",
    "light": "2.5rem",
    "dark": "2.5rem"
  },
  {
    "name": "--ui-ref-space-12",
    "layer": "primitive",
    "light": "3rem",
    "dark": "3rem"
  },
  {
    "name": "--ui-ref-space-16",
    "layer": "primitive",
    "light": "4rem",
    "dark": "4rem"
  },
  {
    "name": "--ui-ref-space-0-5",
    "layer": "primitive",
    "light": "0.125rem",
    "dark": "0.125rem"
  },
  {
    "name": "--ui-ref-space-1-5",
    "layer": "primitive",
    "light": "0.375rem",
    "dark": "0.375rem"
  },
  {
    "name": "--ui-ref-space-2-5",
    "layer": "primitive",
    "light": "0.625rem",
    "dark": "0.625rem"
  },
  {
    "name": "--ui-ref-size-3",
    "layer": "primitive",
    "light": "0.75rem",
    "dark": "0.75rem"
  },
  {
    "name": "--ui-ref-size-4",
    "layer": "primitive",
    "light": "1rem",
    "dark": "1rem"
  },
  {
    "name": "--ui-ref-size-5",
    "layer": "primitive",
    "light": "1.25rem",
    "dark": "1.25rem"
  },
  {
    "name": "--ui-ref-size-6",
    "layer": "primitive",
    "light": "1.5rem",
    "dark": "1.5rem"
  },
  {
    "name": "--ui-ref-size-8",
    "layer": "primitive",
    "light": "2rem",
    "dark": "2rem"
  },
  {
    "name": "--ui-ref-size-9",
    "layer": "primitive",
    "light": "2.25rem",
    "dark": "2.25rem"
  },
  {
    "name": "--ui-ref-size-10",
    "layer": "primitive",
    "light": "2.5rem",
    "dark": "2.5rem"
  },
  {
    "name": "--ui-ref-size-11",
    "layer": "primitive",
    "light": "2.75rem",
    "dark": "2.75rem"
  },
  {
    "name": "--ui-ref-size-px",
    "layer": "primitive",
    "light": "1px",
    "dark": "1px"
  },
  {
    "name": "--ui-ref-size-2px",
    "layer": "primitive",
    "light": "2px",
    "dark": "2px"
  },
  {
    "name": "--ui-ref-size-3-5",
    "layer": "primitive",
    "light": "0.875rem",
    "dark": "0.875rem"
  },
  {
    "name": "--ui-ref-size-4-5",
    "layer": "primitive",
    "light": "1.125rem",
    "dark": "1.125rem"
  },
  {
    "name": "--ui-ref-radius-none",
    "layer": "primitive",
    "light": "0",
    "dark": "0"
  },
  {
    "name": "--ui-ref-radius-sm",
    "layer": "primitive",
    "light": "0.25rem",
    "dark": "0.25rem"
  },
  {
    "name": "--ui-ref-radius-md",
    "layer": "primitive",
    "light": "0.375rem",
    "dark": "0.375rem"
  },
  {
    "name": "--ui-ref-radius-lg",
    "layer": "primitive",
    "light": "0.5rem",
    "dark": "0.5rem"
  },
  {
    "name": "--ui-ref-radius-xl",
    "layer": "primitive",
    "light": "0.75rem",
    "dark": "0.75rem"
  },
  {
    "name": "--ui-ref-radius-full",
    "layer": "primitive",
    "light": "9999px",
    "dark": "9999px"
  },
  {
    "name": "--ui-ref-font-family-sans",
    "layer": "primitive",
    "light": "Assistant, Roboto, \"Helvetica Neue\", sans-serif",
    "dark": "Assistant, Roboto, \"Helvetica Neue\", sans-serif"
  },
  {
    "name": "--ui-ref-font-family-mono",
    "layer": "primitive",
    "light": "ui-monospace, 'JetBrains Mono', 'Cascadia Code', Consolas, monospace",
    "dark": "ui-monospace, 'JetBrains Mono', 'Cascadia Code', Consolas, monospace"
  },
  {
    "name": "--ui-ref-font-size-xs",
    "layer": "primitive",
    "light": "0.75rem",
    "dark": "0.75rem"
  },
  {
    "name": "--ui-ref-font-size-sm",
    "layer": "primitive",
    "light": "0.875rem",
    "dark": "0.875rem"
  },
  {
    "name": "--ui-ref-font-size-md",
    "layer": "primitive",
    "light": "1rem",
    "dark": "1rem"
  },
  {
    "name": "--ui-ref-font-size-lg",
    "layer": "primitive",
    "light": "1.125rem",
    "dark": "1.125rem"
  },
  {
    "name": "--ui-ref-font-size-xl",
    "layer": "primitive",
    "light": "1.25rem",
    "dark": "1.25rem"
  },
  {
    "name": "--ui-ref-font-size-2xl",
    "layer": "primitive",
    "light": "1.5rem",
    "dark": "1.5rem"
  },
  {
    "name": "--ui-ref-font-size-3xl",
    "layer": "primitive",
    "light": "1.875rem",
    "dark": "1.875rem"
  },
  {
    "name": "--ui-ref-font-size-4xl",
    "layer": "primitive",
    "light": "2.25rem",
    "dark": "2.25rem"
  },
  {
    "name": "--ui-ref-font-weight-regular",
    "layer": "primitive",
    "light": "400",
    "dark": "400"
  },
  {
    "name": "--ui-ref-font-weight-medium",
    "layer": "primitive",
    "light": "500",
    "dark": "500"
  },
  {
    "name": "--ui-ref-font-weight-semibold",
    "layer": "primitive",
    "light": "600",
    "dark": "600"
  },
  {
    "name": "--ui-ref-font-weight-bold",
    "layer": "primitive",
    "light": "700",
    "dark": "700"
  },
  {
    "name": "--ui-ref-line-height-tight",
    "layer": "primitive",
    "light": "1.25",
    "dark": "1.25"
  },
  {
    "name": "--ui-ref-line-height-snug",
    "layer": "primitive",
    "light": "1.375",
    "dark": "1.375"
  },
  {
    "name": "--ui-ref-line-height-normal",
    "layer": "primitive",
    "light": "1.5",
    "dark": "1.5"
  },
  {
    "name": "--ui-ref-shadow-sm",
    "layer": "primitive",
    "light": "0 1px 2px 0 rgb(15 23 42 / 0.06)",
    "dark": "0 1px 2px 0 rgb(15 23 42 / 0.06)"
  },
  {
    "name": "--ui-ref-shadow-md",
    "layer": "primitive",
    "light": "0 4px 8px -2px rgb(15 23 42 / 0.10), 0 2px 4px -2px rgb(15 23 42 / 0.06)",
    "dark": "0 4px 8px -2px rgb(15 23 42 / 0.10), 0 2px 4px -2px rgb(15 23 42 / 0.06)"
  },
  {
    "name": "--ui-ref-shadow-lg",
    "layer": "primitive",
    "light": "0 12px 24px -6px rgb(15 23 42 / 0.16), 0 4px 8px -4px rgb(15 23 42 / 0.08)",
    "dark": "0 12px 24px -6px rgb(15 23 42 / 0.16), 0 4px 8px -4px rgb(15 23 42 / 0.08)"
  },
  {
    "name": "--ui-ref-shadow-dark-sm",
    "layer": "primitive",
    "light": "0 1px 2px 0 rgb(0 0 0 / 0.4)",
    "dark": "0 1px 2px 0 rgb(0 0 0 / 0.4)"
  },
  {
    "name": "--ui-ref-shadow-dark-md",
    "layer": "primitive",
    "light": "0 4px 8px -2px rgb(0 0 0 / 0.5)",
    "dark": "0 4px 8px -2px rgb(0 0 0 / 0.5)"
  },
  {
    "name": "--ui-ref-shadow-dark-lg",
    "layer": "primitive",
    "light": "0 12px 24px -6px rgb(0 0 0 / 0.6)",
    "dark": "0 12px 24px -6px rgb(0 0 0 / 0.6)"
  },
  {
    "name": "--ui-ref-z-base",
    "layer": "primitive",
    "light": "0",
    "dark": "0"
  },
  {
    "name": "--ui-ref-z-raised",
    "layer": "primitive",
    "light": "10",
    "dark": "10"
  },
  {
    "name": "--ui-ref-z-dropdown",
    "layer": "primitive",
    "light": "1000",
    "dark": "1000"
  },
  {
    "name": "--ui-ref-z-sticky",
    "layer": "primitive",
    "light": "1100",
    "dark": "1100"
  },
  {
    "name": "--ui-ref-z-overlay",
    "layer": "primitive",
    "light": "1200",
    "dark": "1200"
  },
  {
    "name": "--ui-ref-z-modal",
    "layer": "primitive",
    "light": "1300",
    "dark": "1300"
  },
  {
    "name": "--ui-ref-z-toast",
    "layer": "primitive",
    "light": "1400",
    "dark": "1400"
  },
  {
    "name": "--ui-ref-z-tooltip",
    "layer": "primitive",
    "light": "1500",
    "dark": "1500"
  },
  {
    "name": "--ui-ref-duration-instant",
    "layer": "primitive",
    "light": "50ms",
    "dark": "50ms"
  },
  {
    "name": "--ui-ref-duration-fast",
    "layer": "primitive",
    "light": "120ms",
    "dark": "120ms"
  },
  {
    "name": "--ui-ref-duration-normal",
    "layer": "primitive",
    "light": "200ms",
    "dark": "200ms"
  },
  {
    "name": "--ui-ref-duration-slow",
    "layer": "primitive",
    "light": "320ms",
    "dark": "320ms"
  },
  {
    "name": "--ui-ref-easing-standard",
    "layer": "primitive",
    "light": "cubic-bezier(0.2, 0, 0, 1)",
    "dark": "cubic-bezier(0.2, 0, 0, 1)"
  },
  {
    "name": "--ui-ref-easing-enter",
    "layer": "primitive",
    "light": "cubic-bezier(0, 0, 0.2, 1)",
    "dark": "cubic-bezier(0, 0, 0.2, 1)"
  },
  {
    "name": "--ui-ref-easing-exit",
    "layer": "primitive",
    "light": "cubic-bezier(0.4, 0, 1, 1)",
    "dark": "cubic-bezier(0.4, 0, 1, 1)"
  },
  {
    "name": "--ui-font-family-sans",
    "layer": "semantic",
    "light": "Assistant, Roboto, \"Helvetica Neue\", sans-serif",
    "dark": "Assistant, Roboto, \"Helvetica Neue\", sans-serif"
  },
  {
    "name": "--ui-font-family-mono",
    "layer": "semantic",
    "light": "ui-monospace, 'JetBrains Mono', 'Cascadia Code', Consolas, monospace",
    "dark": "ui-monospace, 'JetBrains Mono', 'Cascadia Code', Consolas, monospace"
  },
  {
    "name": "--ui-font-size-xs",
    "layer": "semantic",
    "light": "0.75rem",
    "dark": "0.75rem"
  },
  {
    "name": "--ui-font-size-sm",
    "layer": "semantic",
    "light": "0.875rem",
    "dark": "0.875rem"
  },
  {
    "name": "--ui-font-size-md",
    "layer": "semantic",
    "light": "1rem",
    "dark": "1rem"
  },
  {
    "name": "--ui-font-size-lg",
    "layer": "semantic",
    "light": "1.125rem",
    "dark": "1.125rem"
  },
  {
    "name": "--ui-font-size-xl",
    "layer": "semantic",
    "light": "1.25rem",
    "dark": "1.25rem"
  },
  {
    "name": "--ui-font-size-2xl",
    "layer": "semantic",
    "light": "1.5rem",
    "dark": "1.5rem"
  },
  {
    "name": "--ui-font-size-3xl",
    "layer": "semantic",
    "light": "1.875rem",
    "dark": "1.875rem"
  },
  {
    "name": "--ui-font-size-4xl",
    "layer": "semantic",
    "light": "2.25rem",
    "dark": "2.25rem"
  },
  {
    "name": "--ui-font-weight-regular",
    "layer": "semantic",
    "light": "400",
    "dark": "400"
  },
  {
    "name": "--ui-font-weight-medium",
    "layer": "semantic",
    "light": "500",
    "dark": "500"
  },
  {
    "name": "--ui-font-weight-semibold",
    "layer": "semantic",
    "light": "600",
    "dark": "600"
  },
  {
    "name": "--ui-font-weight-bold",
    "layer": "semantic",
    "light": "700",
    "dark": "700"
  },
  {
    "name": "--ui-line-height-tight",
    "layer": "semantic",
    "light": "1.25",
    "dark": "1.25"
  },
  {
    "name": "--ui-line-height-snug",
    "layer": "semantic",
    "light": "1.375",
    "dark": "1.375"
  },
  {
    "name": "--ui-line-height-normal",
    "layer": "semantic",
    "light": "1.5",
    "dark": "1.5"
  },
  {
    "name": "--ui-space-3xs",
    "layer": "semantic",
    "light": "0.125rem",
    "dark": "0.125rem"
  },
  {
    "name": "--ui-space-2xs",
    "layer": "semantic",
    "light": "0.25rem",
    "dark": "0.25rem"
  },
  {
    "name": "--ui-space-xs",
    "layer": "semantic",
    "light": "0.375rem",
    "dark": "0.375rem"
  },
  {
    "name": "--ui-space-sm",
    "layer": "semantic",
    "light": "0.5rem",
    "dark": "0.5rem"
  },
  {
    "name": "--ui-space-md",
    "layer": "semantic",
    "light": "0.75rem",
    "dark": "0.75rem"
  },
  {
    "name": "--ui-space-lg",
    "layer": "semantic",
    "light": "1rem",
    "dark": "1rem"
  },
  {
    "name": "--ui-space-xl",
    "layer": "semantic",
    "light": "1.5rem",
    "dark": "1.5rem"
  },
  {
    "name": "--ui-space-2xl",
    "layer": "semantic",
    "light": "2rem",
    "dark": "2rem"
  },
  {
    "name": "--ui-space-3xl",
    "layer": "semantic",
    "light": "3rem",
    "dark": "3rem"
  },
  {
    "name": "--ui-radius-sm",
    "layer": "semantic",
    "light": "0.25rem",
    "dark": "0.25rem"
  },
  {
    "name": "--ui-radius-control",
    "layer": "semantic",
    "light": "0.375rem",
    "dark": "0.375rem"
  },
  {
    "name": "--ui-radius-container",
    "layer": "semantic",
    "light": "0.5rem",
    "dark": "0.5rem"
  },
  {
    "name": "--ui-radius-full",
    "layer": "semantic",
    "light": "9999px",
    "dark": "9999px"
  },
  {
    "name": "--ui-border-width-default",
    "layer": "semantic",
    "light": "1px",
    "dark": "1px"
  },
  {
    "name": "--ui-border-width-strong",
    "layer": "semantic",
    "light": "2px",
    "dark": "2px"
  },
  {
    "name": "--ui-focus-ring-width",
    "layer": "semantic",
    "light": "2px",
    "dark": "2px"
  },
  {
    "name": "--ui-focus-ring-offset",
    "layer": "semantic",
    "light": "2px",
    "dark": "2px"
  },
  {
    "name": "--ui-control-height-sm",
    "layer": "semantic",
    "light": "2rem",
    "dark": "2rem"
  },
  {
    "name": "--ui-control-height-md",
    "layer": "semantic",
    "light": "2.5rem",
    "dark": "2.5rem"
  },
  {
    "name": "--ui-control-height-lg",
    "layer": "semantic",
    "light": "2.75rem",
    "dark": "2.75rem"
  },
  {
    "name": "--ui-control-padding-inline-sm",
    "layer": "semantic",
    "light": "0.625rem",
    "dark": "0.625rem"
  },
  {
    "name": "--ui-control-padding-inline-md",
    "layer": "semantic",
    "light": "0.75rem",
    "dark": "0.75rem"
  },
  {
    "name": "--ui-control-padding-inline-lg",
    "layer": "semantic",
    "light": "1rem",
    "dark": "1rem"
  },
  {
    "name": "--ui-control-font-size-sm",
    "layer": "semantic",
    "light": "0.875rem",
    "dark": "0.875rem"
  },
  {
    "name": "--ui-control-font-size-md",
    "layer": "semantic",
    "light": "0.875rem",
    "dark": "0.875rem"
  },
  {
    "name": "--ui-control-font-size-lg",
    "layer": "semantic",
    "light": "1rem",
    "dark": "1rem"
  },
  {
    "name": "--ui-control-gap-sm",
    "layer": "semantic",
    "light": "0.375rem",
    "dark": "0.375rem"
  },
  {
    "name": "--ui-control-gap-md",
    "layer": "semantic",
    "light": "0.5rem",
    "dark": "0.5rem"
  },
  {
    "name": "--ui-control-gap-lg",
    "layer": "semantic",
    "light": "0.625rem",
    "dark": "0.625rem"
  },
  {
    "name": "--ui-icon-size-sm",
    "layer": "semantic",
    "light": "1rem",
    "dark": "1rem"
  },
  {
    "name": "--ui-icon-size-md",
    "layer": "semantic",
    "light": "1.25rem",
    "dark": "1.25rem"
  },
  {
    "name": "--ui-icon-size-lg",
    "layer": "semantic",
    "light": "1.5rem",
    "dark": "1.5rem"
  },
  {
    "name": "--ui-z-raised",
    "layer": "semantic",
    "light": "10",
    "dark": "10"
  },
  {
    "name": "--ui-z-dropdown",
    "layer": "semantic",
    "light": "1000",
    "dark": "1000"
  },
  {
    "name": "--ui-z-sticky",
    "layer": "semantic",
    "light": "1100",
    "dark": "1100"
  },
  {
    "name": "--ui-z-overlay",
    "layer": "semantic",
    "light": "1200",
    "dark": "1200"
  },
  {
    "name": "--ui-z-modal",
    "layer": "semantic",
    "light": "1300",
    "dark": "1300"
  },
  {
    "name": "--ui-z-toast",
    "layer": "semantic",
    "light": "1400",
    "dark": "1400"
  },
  {
    "name": "--ui-z-tooltip",
    "layer": "semantic",
    "light": "1500",
    "dark": "1500"
  },
  {
    "name": "--ui-motion-duration-instant",
    "layer": "semantic",
    "light": "50ms",
    "dark": "50ms"
  },
  {
    "name": "--ui-motion-duration-fast",
    "layer": "semantic",
    "light": "120ms",
    "dark": "120ms"
  },
  {
    "name": "--ui-motion-duration-normal",
    "layer": "semantic",
    "light": "200ms",
    "dark": "200ms"
  },
  {
    "name": "--ui-motion-duration-slow",
    "layer": "semantic",
    "light": "320ms",
    "dark": "320ms"
  },
  {
    "name": "--ui-motion-easing-standard",
    "layer": "semantic",
    "light": "cubic-bezier(0.2, 0, 0, 1)",
    "dark": "cubic-bezier(0.2, 0, 0, 1)"
  },
  {
    "name": "--ui-motion-easing-enter",
    "layer": "semantic",
    "light": "cubic-bezier(0, 0, 0.2, 1)",
    "dark": "cubic-bezier(0, 0, 0.2, 1)"
  },
  {
    "name": "--ui-motion-easing-exit",
    "layer": "semantic",
    "light": "cubic-bezier(0.4, 0, 1, 1)",
    "dark": "cubic-bezier(0.4, 0, 1, 1)"
  },
  {
    "name": "--ui-color-bg",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#111723"
  },
  {
    "name": "--ui-color-surface",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#1d2535"
  },
  {
    "name": "--ui-color-surface-subtle",
    "layer": "semantic",
    "light": "#f8f9fb",
    "dark": "#1d2535"
  },
  {
    "name": "--ui-color-surface-muted",
    "layer": "semantic",
    "light": "#f1f3f6",
    "dark": "#2b3549"
  },
  {
    "name": "--ui-color-surface-raised",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#2b3549"
  },
  {
    "name": "--ui-color-surface-hover",
    "layer": "semantic",
    "light": "#f1f3f6",
    "dark": "#2b3549"
  },
  {
    "name": "--ui-color-surface-active",
    "layer": "semantic",
    "light": "#e4e7ed",
    "dark": "#4a5466"
  },
  {
    "name": "--ui-color-text",
    "layer": "semantic",
    "light": "#1d2535",
    "dark": "#f8f9fb"
  },
  {
    "name": "--ui-color-text-muted",
    "layer": "semantic",
    "light": "#636d7e",
    "dark": "#a7acaf"
  },
  {
    "name": "--ui-color-text-subtle",
    "layer": "semantic",
    "light": "#636d7e",
    "dark": "#a7acaf"
  },
  {
    "name": "--ui-color-text-disabled",
    "layer": "semantic",
    "light": "#a7acaf",
    "dark": "#636d7e"
  },
  {
    "name": "--ui-color-text-inverse",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#1d2535"
  },
  {
    "name": "--ui-color-border",
    "layer": "semantic",
    "light": "#e4e7ed",
    "dark": "#2b3549"
  },
  {
    "name": "--ui-color-border-control",
    "layer": "semantic",
    "light": "#848d9d",
    "dark": "#848d9d"
  },
  {
    "name": "--ui-color-border-control-hover",
    "layer": "semantic",
    "light": "#4a5466",
    "dark": "#cdd2db"
  },
  {
    "name": "--ui-color-control-bg",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#1d2535"
  },
  {
    "name": "--ui-color-control-bg-disabled",
    "layer": "semantic",
    "light": "#f1f3f6",
    "dark": "#2b3549"
  },
  {
    "name": "--ui-color-primary",
    "layer": "semantic",
    "light": "#1a74c9",
    "dark": "#4aa3ef"
  },
  {
    "name": "--ui-color-primary-hover",
    "layer": "semantic",
    "light": "#155ea6",
    "dark": "#72b8f2"
  },
  {
    "name": "--ui-color-primary-active",
    "layer": "semantic",
    "light": "#004b9e",
    "dark": "#a8d3f6"
  },
  {
    "name": "--ui-color-primary-contrast",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#111723"
  },
  {
    "name": "--ui-color-primary-subtle",
    "layer": "semantic",
    "light": "#e9f4fc",
    "dark": "#0a2747"
  },
  {
    "name": "--ui-color-primary-subtle-hover",
    "layer": "semantic",
    "light": "#d3e9fa",
    "dark": "#0d3d6e"
  },
  {
    "name": "--ui-color-primary-text",
    "layer": "semantic",
    "light": "#155ea6",
    "dark": "#72b8f2"
  },
  {
    "name": "--ui-color-danger",
    "layer": "semantic",
    "light": "#dc2626",
    "dark": "#f87171"
  },
  {
    "name": "--ui-color-danger-hover",
    "layer": "semantic",
    "light": "#b91c1c",
    "dark": "#fca5a5"
  },
  {
    "name": "--ui-color-danger-active",
    "layer": "semantic",
    "light": "#991b1b",
    "dark": "#fecaca"
  },
  {
    "name": "--ui-color-danger-contrast",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#111723"
  },
  {
    "name": "--ui-color-danger-subtle",
    "layer": "semantic",
    "light": "#fef2f2",
    "dark": "#450a0a"
  },
  {
    "name": "--ui-color-danger-text",
    "layer": "semantic",
    "light": "#b91c1c",
    "dark": "#fca5a5"
  },
  {
    "name": "--ui-color-success",
    "layer": "semantic",
    "light": "#008752",
    "dark": "#3fae7c"
  },
  {
    "name": "--ui-color-success-contrast",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#111723"
  },
  {
    "name": "--ui-color-success-subtle",
    "layer": "semantic",
    "light": "#e8f6ef",
    "dark": "#032819"
  },
  {
    "name": "--ui-color-success-text",
    "layer": "semantic",
    "light": "#006c42",
    "dark": "#5fbf8f"
  },
  {
    "name": "--ui-color-warning",
    "layer": "semantic",
    "light": "#685e1b",
    "dark": "#bfae38"
  },
  {
    "name": "--ui-color-warning-contrast",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#111723"
  },
  {
    "name": "--ui-color-warning-subtle",
    "layer": "semantic",
    "light": "#faf8e8",
    "dark": "#29230a"
  },
  {
    "name": "--ui-color-warning-text",
    "layer": "semantic",
    "light": "#554c1a",
    "dark": "#d4c65a"
  },
  {
    "name": "--ui-color-info",
    "layer": "semantic",
    "light": "#155ea6",
    "dark": "#4aa3ef"
  },
  {
    "name": "--ui-color-info-contrast",
    "layer": "semantic",
    "light": "#ffffff",
    "dark": "#111723"
  },
  {
    "name": "--ui-color-info-subtle",
    "layer": "semantic",
    "light": "#e9f4fc",
    "dark": "#0a2747"
  },
  {
    "name": "--ui-color-info-text",
    "layer": "semantic",
    "light": "#004b9e",
    "dark": "#72b8f2"
  },
  {
    "name": "--ui-color-focus-ring",
    "layer": "semantic",
    "light": "#2490ed",
    "dark": "#4aa3ef"
  },
  {
    "name": "--ui-color-backdrop",
    "layer": "semantic",
    "light": "rgb(15 23 42 / 0.5)",
    "dark": "rgb(0 0 0 / 0.6)"
  },
  {
    "name": "--ui-shadow-sm",
    "layer": "semantic",
    "light": "0 1px 2px 0 rgb(15 23 42 / 0.06)",
    "dark": "0 1px 2px 0 rgb(0 0 0 / 0.4)"
  },
  {
    "name": "--ui-shadow-md",
    "layer": "semantic",
    "light": "0 4px 8px -2px rgb(15 23 42 / 0.10), 0 2px 4px -2px rgb(15 23 42 / 0.06)",
    "dark": "0 4px 8px -2px rgb(0 0 0 / 0.5)"
  },
  {
    "name": "--ui-shadow-lg",
    "layer": "semantic",
    "light": "0 12px 24px -6px rgb(15 23 42 / 0.16), 0 4px 8px -4px rgb(15 23 42 / 0.08)",
    "dark": "0 12px 24px -6px rgb(0 0 0 / 0.6)"
  },
  {
    "name": "--ui-button-radius",
    "layer": "component",
    "light": "var(--ui-radius-control)",
    "dark": "var(--ui-radius-control)"
  },
  {
    "name": "--ui-button-font-weight",
    "layer": "component",
    "light": "var(--ui-font-weight-medium)",
    "dark": "var(--ui-font-weight-medium)"
  },
  {
    "name": "--ui-button-primary-bg",
    "layer": "component",
    "light": "var(--ui-color-primary)",
    "dark": "var(--ui-color-primary)"
  },
  {
    "name": "--ui-button-primary-bg-hover",
    "layer": "component",
    "light": "var(--ui-color-primary-hover)",
    "dark": "var(--ui-color-primary-hover)"
  },
  {
    "name": "--ui-button-primary-bg-active",
    "layer": "component",
    "light": "var(--ui-color-primary-active)",
    "dark": "var(--ui-color-primary-active)"
  },
  {
    "name": "--ui-button-primary-text",
    "layer": "component",
    "light": "var(--ui-color-primary-contrast)",
    "dark": "var(--ui-color-primary-contrast)"
  },
  {
    "name": "--ui-button-primary-border",
    "layer": "component",
    "light": "transparent",
    "dark": "transparent"
  },
  {
    "name": "--ui-button-secondary-bg",
    "layer": "component",
    "light": "var(--ui-color-surface)",
    "dark": "var(--ui-color-surface)"
  },
  {
    "name": "--ui-button-secondary-bg-hover",
    "layer": "component",
    "light": "var(--ui-color-surface-hover)",
    "dark": "var(--ui-color-surface-hover)"
  },
  {
    "name": "--ui-button-secondary-bg-active",
    "layer": "component",
    "light": "var(--ui-color-surface-active)",
    "dark": "var(--ui-color-surface-active)"
  },
  {
    "name": "--ui-button-secondary-text",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-button-secondary-border",
    "layer": "component",
    "light": "var(--ui-color-border-control)",
    "dark": "var(--ui-color-border-control)"
  },
  {
    "name": "--ui-button-ghost-bg",
    "layer": "component",
    "light": "transparent",
    "dark": "transparent"
  },
  {
    "name": "--ui-button-ghost-bg-hover",
    "layer": "component",
    "light": "var(--ui-color-surface-hover)",
    "dark": "var(--ui-color-surface-hover)"
  },
  {
    "name": "--ui-button-ghost-bg-active",
    "layer": "component",
    "light": "var(--ui-color-surface-active)",
    "dark": "var(--ui-color-surface-active)"
  },
  {
    "name": "--ui-button-ghost-text",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-button-ghost-border",
    "layer": "component",
    "light": "transparent",
    "dark": "transparent"
  },
  {
    "name": "--ui-button-danger-bg",
    "layer": "component",
    "light": "var(--ui-color-danger)",
    "dark": "var(--ui-color-danger)"
  },
  {
    "name": "--ui-button-danger-bg-hover",
    "layer": "component",
    "light": "var(--ui-color-danger-hover)",
    "dark": "var(--ui-color-danger-hover)"
  },
  {
    "name": "--ui-button-danger-bg-active",
    "layer": "component",
    "light": "var(--ui-color-danger-active)",
    "dark": "var(--ui-color-danger-active)"
  },
  {
    "name": "--ui-button-danger-text",
    "layer": "component",
    "light": "var(--ui-color-danger-contrast)",
    "dark": "var(--ui-color-danger-contrast)"
  },
  {
    "name": "--ui-button-danger-border",
    "layer": "component",
    "light": "transparent",
    "dark": "transparent"
  },
  {
    "name": "--ui-input-bg",
    "layer": "component",
    "light": "var(--ui-color-control-bg)",
    "dark": "var(--ui-color-control-bg)"
  },
  {
    "name": "--ui-input-bg-disabled",
    "layer": "component",
    "light": "var(--ui-color-control-bg-disabled)",
    "dark": "var(--ui-color-control-bg-disabled)"
  },
  {
    "name": "--ui-input-text",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-input-placeholder",
    "layer": "component",
    "light": "var(--ui-color-text-subtle)",
    "dark": "var(--ui-color-text-subtle)"
  },
  {
    "name": "--ui-input-border",
    "layer": "component",
    "light": "var(--ui-color-border-control)",
    "dark": "var(--ui-color-border-control)"
  },
  {
    "name": "--ui-input-border-hover",
    "layer": "component",
    "light": "var(--ui-color-border-control-hover)",
    "dark": "var(--ui-color-border-control-hover)"
  },
  {
    "name": "--ui-input-border-focus",
    "layer": "component",
    "light": "var(--ui-color-primary)",
    "dark": "var(--ui-color-primary)"
  },
  {
    "name": "--ui-input-border-invalid",
    "layer": "component",
    "light": "var(--ui-color-danger)",
    "dark": "var(--ui-color-danger)"
  },
  {
    "name": "--ui-input-radius",
    "layer": "component",
    "light": "var(--ui-radius-control)",
    "dark": "var(--ui-radius-control)"
  },
  {
    "name": "--ui-form-field-gap",
    "layer": "component",
    "light": "var(--ui-space-2xs)",
    "dark": "var(--ui-space-2xs)"
  },
  {
    "name": "--ui-form-field-label-color",
    "layer": "component",
    "light": "var(--ui-color-text)",
    "dark": "var(--ui-color-text)"
  },
  {
    "name": "--ui-form-field-label-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-sm)",
    "dark": "var(--ui-font-size-sm)"
  },
  {
    "name": "--ui-form-field-label-font-weight",
    "layer": "component",
    "light": "var(--ui-font-weight-medium)",
    "dark": "var(--ui-font-weight-medium)"
  },
  {
    "name": "--ui-form-field-hint-color",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-form-field-error-color",
    "layer": "component",
    "light": "var(--ui-color-danger-text)",
    "dark": "var(--ui-color-danger-text)"
  },
  {
    "name": "--ui-form-field-message-font-size",
    "layer": "component",
    "light": "var(--ui-font-size-xs)",
    "dark": "var(--ui-font-size-xs)"
  },
  {
    "name": "--ui-form-field-affix-color",
    "layer": "component",
    "light": "var(--ui-color-text-muted)",
    "dark": "var(--ui-color-text-muted)"
  },
  {
    "name": "--ui-checkbox-size",
    "layer": "component",
    "light": "var(--ui-icon-size-sm)",
    "dark": "var(--ui-icon-size-sm)"
  },
  {
    "name": "--ui-checkbox-radius",
    "layer": "component",
    "light": "var(--ui-radius-sm)",
    "dark": "var(--ui-radius-sm)"
  },
  {
    "name": "--ui-checkbox-bg",
    "layer": "component",
    "light": "var(--ui-color-control-bg)",
    "dark": "var(--ui-color-control-bg)"
  },
  {
    "name": "--ui-checkbox-border",
    "layer": "component",
    "light": "var(--ui-color-border-control)",
    "dark": "var(--ui-color-border-control)"
  },
  {
    "name": "--ui-checkbox-checked-bg",
    "layer": "component",
    "light": "var(--ui-color-primary)",
    "dark": "var(--ui-color-primary)"
  },
  {
    "name": "--ui-checkbox-checked-color",
    "layer": "component",
    "light": "var(--ui-color-primary-contrast)",
    "dark": "var(--ui-color-primary-contrast)"
  },
  {
    "name": "--ui-checkbox-invalid-border",
    "layer": "component",
    "light": "var(--ui-color-danger)",
    "dark": "var(--ui-color-danger)"
  },
  {
    "name": "--ui-radio-size",
    "layer": "component",
    "light": "var(--ui-icon-size-sm)",
    "dark": "var(--ui-icon-size-sm)"
  },
  {
    "name": "--ui-radio-bg",
    "layer": "component",
    "light": "var(--ui-color-control-bg)",
    "dark": "var(--ui-color-control-bg)"
  },
  {
    "name": "--ui-radio-border",
    "layer": "component",
    "light": "var(--ui-color-border-control)",
    "dark": "var(--ui-color-border-control)"
  },
  {
    "name": "--ui-radio-checked-color",
    "layer": "component",
    "light": "var(--ui-color-primary)",
    "dark": "var(--ui-color-primary)"
  },
  {
    "name": "--ui-radio-invalid-border",
    "layer": "component",
    "light": "var(--ui-color-danger)",
    "dark": "var(--ui-color-danger)"
  },
  {
    "name": "--ui-switch-track-width",
    "layer": "component",
    "light": "var(--ui-control-height-md)",
    "dark": "var(--ui-control-height-md)"
  },
  {
    "name": "--ui-switch-track-height",
    "layer": "component",
    "light": "var(--ui-icon-size-md)",
    "dark": "var(--ui-icon-size-md)"
  },
  {
    "name": "--ui-switch-track-bg",
    "layer": "component",
    "light": "var(--ui-color-border-control)",
    "dark": "var(--ui-color-border-control)"
  },
  {
    "name": "--ui-switch-track-checked-bg",
    "layer": "component",
    "light": "var(--ui-color-primary)",
    "dark": "var(--ui-color-primary)"
  },
  {
    "name": "--ui-switch-thumb-bg",
    "layer": "component",
    "light": "var(--ui-color-control-bg)",
    "dark": "var(--ui-color-control-bg)"
  },
  {
    "name": "--ui-switch-invalid-outline",
    "layer": "component",
    "light": "var(--ui-color-danger)",
    "dark": "var(--ui-color-danger)"
  },
  {
    "name": "--ui-spinner-track-color",
    "layer": "component",
    "light": "var(--ui-color-border)",
    "dark": "var(--ui-color-border)"
  },
  {
    "name": "--ui-spinner-stroke-width",
    "layer": "component",
    "light": "var(--ui-border-width-strong)",
    "dark": "var(--ui-border-width-strong)"
  }
];
